### ISSUE TITLE
Wrapping code in early React challenges - problem with trailing comments

### ISSUE THREAD

**Issue by coreywhite** [bonham000/fcc-react-tests-module#106]
Hello! First, I wanted to say that I love the new challenges so far. Haven't looked through them all yet, but I really like what I've seen so far.

I noticed an issue where a trailing comment line in the early React challenges will break the transpilation. This is due to the appended code that ends and executes the wrapping IIFE being absorbed into the comment line in the user's code:

```
	const prepend = `(function() {`
	const apend = `; return JSX })()`
	const modifiedCode = prepend.concat(code).concat(apend);
```

Unfortunately, the user has no reason to expect this behavior. A trailing comment looks like it should be valid code. So when their transpilation fails, they will most likely look for other culprits and ignore the innocent seeming comment. For example, this code fails in React Challenge 4:

```
const JSX = (
<div>
	<h1>Hello World</h1>
	<p>Lets render this to the DOM</p>
</div>
);
// change code below this line
ReactDOM.render(JSX, document.getElementById('challenge-node'));
//Yay, I'm done!
````

Removing that final comment line allows that code to pass, but it shouldn't be necessary.

I submitted a pull request to fix this in the 8 React challenges I saw that had this issue. My fix was just to add a newline character prior to the rest of the appended code. I took this approach to keep this code in line with what is already done in the Redux challenges (and the Redux challenge template):

```
	const prepend = `(function() {`
	const apend = `;\n return JSX })()`
	const modifiedCode = prepend.concat(code).concat(apend);
```

Another approach would be to use ES6 template string interpolation. I didn't do that, to stay consistent with the rest of the code, but please let me know if you would prefer that I submit a different pull request with that approach. It would look something like this:
```
	const modifiedCode = `
		(function() {
			${code}
			return JSX;
		})();
	`;
```

Thank you very much!

**Comment by bonham000** [comment]
Yes this was good to catch, I just merged your PR. I think `\n` is the way to go for consistency with the rest of the challenges. I just glanced through and I think all other instances like this include the new line but if you see any more feel free to comment here or send another PR in. Thanks!
