### ISSUE TITLE
React Challenge #41 ternary operator fails last test

### ISSUE THREAD

**Issue by planigan** [bonham000/fcc-react-tests-module#113]
This code works:

```js
return this.state.display ? (
	   	<div>
	   		<button onClick={this.toggleDisplay}>Toggle Display</button>
	   		<h1>Displayed!</h1>
	   	</div>
      ) : (
	   	<div>
	   		<button onClick={this.toggleDisplay}>Toggle Display</button>
	   	</div>
      );
```

But fails last test. I think I like ternary operators too much :smile:

**Comment by bonham000** [comment]
Yes that's because it's specifically asking for an `if/else`, however I'll make a note that using a ternary will fail here even though it does create the desired functionality. Ternary is then covered directly in 44.

**Comment by planigan** [comment]
:+1: Yes, I opened this issue before I got to the ternary discussion. I kinda figured that it was because it was specifically asking for if/else.
