### ISSUE TITLE
Confusing syntax on challenge 07

### ISSUE THREAD

**Issue by tuxitop** [bonham000/fcc-react-tests-module#116]
This is part of the sample code:
```javascript
const { customClass } = props;
  return (
    <div className={customClass} />
  );
```
The destructuring assignment syntax seems to be a little confusing to a beginner. although you have mentioned it in the comments, but it would be better to also include a link for more information.
Of course a more beginner friendly approach would be using the folowing syntax, removing the assignment.
```javascript
return (
    <div className={props.customClass} />
  );
```
I think it's better to include this syntax in the comments or in another example and mention that these two syntaxes will produce the same output.

**Comment by bonham000** [comment]
Ok, yes I agree with you looking at this now. Thanks for your comments! I've gone through and made some updates to this challenge to make it easier to understand.
