### ISSUE TITLE
Challenge 19

### ISSUE THREAD

**Issue by tuxitop** [bonham000/fcc-react-tests-module#117]
In the instructions it's asked to assign a "string value that is at least 8 characters" to the tempPassword:
> give ReturnTempPassword a prop of tempPassword and assign it a value of a string that is at least 8 characters long.

However there is a test case that requires the password to be exactly `serrPbqrPnzc`.
> The ReturnTempPassword component should display the tempPassword serrPbqrPnzc within strong tags.

**Comment by profoundhub** [comment]
That must be new, I don't remember setting the tempPassword to "serrPbqrPnzc".
