### ISSUE TITLE
Challenge 26 test case 4

### ISSUE THREAD

**Issue by tuxitop** [bonham000/fcc-react-tests-module#122]
This challenge asks to define a method using ES6 arrow functions. here's the method:
```javascript
setMessage = () => {
    this.setState({message:"Goodbye!"})
}
```
Although this works but the test case will fail because I forgot to place a tiny `;` at the end of the statement. 

In my opinion, the semicolon shouldn't cause a test case to fail, it's the linter's job to show errors for this sorts of stuff. and it would also confuse people because it says you should use an arrow function, it doesn't say you forgot a semicolon.

**Comment by bonham000** [comment]
Yeah, you're right. I've updated these tests now.
