### ISSUE TITLE
Challenge 36 - componentWillRecieveProps

### ISSUE THREAD

**Issue by tuxitop** [bonham000/fcc-react-tests-module#124]
Hello,
first of all I wish you a happy new year ahead. :)

In the "Intro" section of the challenge it is stated that

> This method receives the new props as a nextProps argument ...

However technicaly what happens is: This method receives the new props as **an argument**. 

Although the argument is usually called `nextProps`, in fact it can be called anything like `newProps` or `futureProps`.

Similarly the test cases require the argument to be called `nextProps`, changing the argument's name to anything else will show the right message to the console but it will cause the test case to fail.

**Comment by bonham000** [comment]
That's right, you're correct about this! I'll edit this challenge to explain that while it is usually called `nextProps` it can be called anything.
