### ISSUE TITLE
20: Using Props with Stateless Functional Components

### ISSUE THREAD

**Issue by nativedone** [bonham000/fcc-react-tests-module#126]
Hi guys, firstly thanks for this great material.

From my point of view, the 20 challenge has a problem on its last test. It says:

> The Camper component should contain a p element with only the text from the **name prop**.

Pay attention that I highlighted **name prop**, because It does not says **default** name prop. 

But, the above test fails when the CampSite component returns Camper component specifying almost any string value to its name prop. Except, if we pass the **exact** value of the default name prop.

```
<Camper name='Any name'/>   {*/ ERROR /*}
<Camper />   {*/ Works as expected /*}
<Camper name='CamperBot'/>    {*/ Works as expected /*}
```

Looking on the source code, I saw that the problem is on the assertion of the test 5: 

```
// test 5:
try {
	assert.strictEqual(mockedComponent.contains(<p>CamperBot</p>), true, error_5);
	testResults[5].status = true;
}
```

I think may be this can be fixed changing it to:
```
// test 5:
try {
	assert(typeof mockedComponent.props().props.name === 'string', true, error_5);
	testResults[5].status = true;
}
```

**Comment by bonham000** [comment]
Nice catch I think this can be improved too. We'll have to grab the props off the `Camper` component so I've changed the test line to the following:

``` javascript
assert.strictEqual(mockedComponent.contains(<p>{mockedComponent.find('Camper').props().name}</p>), true, error_5);
```

I think this gives us what we're looking for. It's updated on the live app now if you want to take a look and see if it's working.

**Comment by nativedone** [comment]
Works perfectly! Nice solution :)

**Comment by bonham000** [comment]
Awesome, thanks!
