### ISSUE TITLE
26: Bind 'this' with an ES6 Arrow Function

### ISSUE THREAD

**Issue by nativedone** [bonham000/fcc-react-tests-module#127]
I don't know if it is a problem, but the tests all pass if the student still uses `.bind(this)` on constructor as shown below:  

```
class MyComponent extends React.Component {
	constructor(props) {
		super(props);
		// change code below this line
		this.state = { message: 'Hello!' };
    this.setMessage = this.setMessage.bind(this);
		// change code above this line
	}
	// change code below this line
	setMessage = () => {
  	this.setState({message: 'Goodbye!'});
  }
	// change code above this line
	render() {
  	return (
	    <div>
        <button onClick = {this.setMessage}>Click Me</button>
        <h1>{this.state.message}</h1>
	    </div>
    );
  }
};
```

May be this `double bind` could be done by someone who are still having little contact with ES6 sintax, arrow functions ...

**Comment by bonham000** [comment]
Hmm... you're right about this. However, if they don't write the arrow function the tests would still fail regardless. The only thing I can think we could do about this is writing a test to explicitly check that they are not binding `this` in the constructor. Do you think that would be worth adding?

**Comment by nativedone** [comment]
Also, I think they could bind `this` on the direct call:

`<button onClick = {this.setMessage.bind(this)}>Click Me</button>`

But, the instructions are clear on which parts of the code should be changed.

Any way, I really don't know if the challenge will be better with these extra tests. I only touched that point because may be it was important to you.

As I don't have enough experience to give you a solid opinion on that topic... feel free to close this issue or wait someone else opinion.

**Comment by bonham000** [comment]
Yes that also is a good point. I think I will leave it for now because you still have to write an arrow function to pass the challenge even if you try to use one of these alternative methods. Because the goal of the challenge is to write an arrow function and you would have to go out of your way to add one of these other solutions, I think it's okay to leave it like this for now. Thanks a lot for pointing this issue out thought!
