### ISSUE TITLE
Redux 09 - Ambiguous wording

### ISSUE THREAD

**Issue by oksas** [bonham000/fcc-react-tests-module#136]
Hey! Thank yall for putting these together; I'm doing the Redux modules to finally get my hands dirty with Redux and these are super helpful 👍 👍 

I just wanted to bring attention to some of the wording on the Redux 09 challenge. The beginning of the instructions reads:

> Write the `store.subscribe()` method, passing in a function which logs a message to the console everytime the store receives an action. 

I think what would be more clear would be to say something like:

> Write a callback function that logs a message to the console every time the store receives an action, and pass this function in to the `store.subscribe()` method.

As it stands currently, it kind of sounds like the test is asking you to write _the_ `store.subscribe` method itself, when what it's really looking for is just a callback function that gets passed to `store.subscribe`. Hope that makes sense! I'd be happy to submit a PR with the changes if others feel similarly 💃

**Comment by bonham000** [comment]
Yeah, I think this is a good improvement! I just changed it to the sentence you suggested and updated it. Thanks for this, we haven't gotten a lot of people reviewing Redux and React/Redux so please add any other comments or feedback you come across.
