### ISSUE TITLE
React 46

### ISSUE THREAD

**Issue by dgrcode** [bonham000/fcc-react-tests-module#137]
When reading the instructions it says:

> **Instructions**: Here we've created a simple controlled input and styled its border. We want to style this border red if the user types _**too much**_ text in the input box....

Even though the last test says that more than 15 characters is considered too much, I would add a small indication on the instruction, so it is self-explanatory.

**Comment by bonham000** [comment]
Yes I agree! I wrote this recently I definitely meant to mentioned directly how long to make 'too long'. Fixed it now!
