### ISSUE TITLE
React 50: ReactDOM.renderToString is deprecated

### ISSUE THREAD

**Issue by dgrcode** [bonham000/fcc-react-tests-module#138]
It was the first time I was going to use the method `renderToString()`, and therefore I went to the docs to read how to use the method and any other relevant information.

When I went to [`ReactDOM` docs][1], there were no method called `ReactDOM.renderToString()`, but I saw the module `ReactDOMServer` and I wanted to know how to render React on the server, so I checked it. On [`ReactDOMServer` docs][2] there is a method `ReactDOMServer.renderToString()`. The explanation of the method is:

> Render a React element to its initial HTML. This should only be used on the server. React will return an HTML string. You can use this method to generate HTML on the server and send the markup down on the initial request for faster page loads and to allow search engines to crawl your pages for SEO purposes.
> 
> If you call ReactDOM.render() on a node that already has this server-rendered markup, React will preserve it and only attach event handlers, allowing you to have a very performant first-load experience.

And this is just what I was looking for on `ReactDOM`. I kept investigating about it and found that it was deprecated in v0.14 and [removed in v15.0.0][3]:
> Deprecated APIs are removed from the `React` top-level export: `findDOMNode`, `render`, **`renderToString`**, `renderToStaticMarkup`, and `unmountComponentAtNode`. As a reminder, they are now available on `ReactDOM` and `ReactDOMServer`. (@jimfb in #5832)

I think this challenge should be modified to make `ReactDOMServer.renderToString()` the valid solution. In addition I would make a remark about `ReactDOM.renderToString()` being deprecated since v15.0.0.

Let me know if I could help with anything here!

[1]: https://facebook.github.io/react/docs/react-dom.html
[2]: https://facebook.github.io/react/docs/react-dom-server.html
[3]: https://github.com/facebook/react/releases/tag/v15.0.0

**Comment by bonham000** [comment]
Hey @dgrcode this is great, thanks a lot for pointing this out. I really thought I had checked thoroughly when writing this challenge because I've never personally used the `renderToString` method... but I guess I didn't or maybe I saw old documentation.

Either way, I'm going to go in and just update this challenge to say `ReactDOMServer.renderToString`. Thanks for finding this!
