### ISSUE TITLE
Redux 11: minor improvements

### ISSUE THREAD

**Issue by dgrcode** [bonham000/fcc-react-tests-module#140]
I think the current description is clear enough to be solved without any confusion. However, I would like to point out two possible improvements.

1. In the second paragraph it tells to add a type as we've been doing, but it doesn't specify the value of the type. From the instructions to modify the reducer it's obvious that the value should be `ADD_NOTE`, but I think it could be stated explicitly when defining the action creator. I suggest something on the lines of:
>[...] Finish the body of the `addNoteText()` function so that it returns an `action` object which includes a `type` like we're used to, _**with the value of `ADD_NOTE`**_, but let's also pass [...]

2. In the third paragraph it tells to return a property of `action` as the new `state`. I think the name of the property to be returned should be highlighted as code, so it says "return the `text` property", meaning that "text" is the name of the property to be returned. I think currently it could be understood as "return the text property", meaning that you return a property containing a text/string.

I don't think those changes are a must, but they could make the description a bit clearer.

**Comment by bonham000** [comment]
@dgrcode I agree with both of these points! Good catches. I've updated the challenge to reflect your observations.
