### ISSUE TITLE
Text Formatting Instructions Problem 4

### ISSUE THREAD

**Issue by benschac** [bonham000/fcc-react-tests-module#147]
Just a suggestion.  Maybe breakdown the formatting of the instruction a little more so it's easier to break down and read.

ex.
ReactDOM offers a simple method to render React elements to the DOM which looks like this: ReactDOM.render(componentToRender, targetNode). The first argument is the React element or component that you want to render. The second argument is the DOM node that you want to render the component within. As you would expect, ReactDOM.render() must be called after the part in your code where you declared the element you want to render.

to:

```ReactDOM.render(componentToRender, targetNode)``` is ReactDOM's simple method to render React elements to the DOM.

1. The first argument is the React element or component that you want to render.
2. The second argument is the DOM node that you want to render the component within.

ReactDOM.render() must be called after your declared variables that you want to render.

**Comment by bonham000** [comment]
Ok! I think this is a generally good suggestion. I applied some edits to make it look more like this. Thanks for the feedback!
