### ISSUE TITLE
Custom URL Slugs

### ISSUE THREAD

**Issue by benschac** [bonham000/fcc-react-tests-module#151]
It would be a nice feature to have a custom URL Slug so the User could save where they are in their progress.

```
http://hysterical-amusement.surge.sh/
```
would be something like

```
http://hysterical-amusement.surge.sh/problem-1
```

**Comment by bonham000** [comment]
I agree, eventually when these are merged into the FCC platform they should behave just like the current FCC challenges which provide this feature.
