### ISSUE TITLE
React Problem 7 - As a user I want to immediately code a concept that I learned.

### ISSUE THREAD

**Issue by benschac** [bonham000/fcc-react-tests-module#152]
Just a suggestion.  Maybe don't introduce `props` if it's not going to be used in the problem.  Not that it's a bad thing to introduce something as a sidenote, but for me as a user it's an odd flow.

**Comment by bonham000** [comment]
Yeah this is a good point too. I think originally `props` was included here to allow people to see it to make it easier to understand later, but I think it actually is more confusing since you don't have to use it in this challenge. I've just removed the references to `props` here.
