### ISSUE TITLE
React Problem 8 - As a User I should have to code the concept I just learned.

### ISSUE THREAD

**Issue by benschac** [bonham000/fcc-react-tests-module#153]
Just a suggestion. But from a users perspective, make them write the render function.

```
class MyComponent extends React.Component {
	constructor(props) {
		super(props);
	}
  render() {
    return (
	    // change code below this line
			<div>
        <h1>Hello React!</h1>
      </div>


	    // change code above this line
    );
  }
};
```

would be

```
class MyComponent extends React.Component {

 
	    // change code above this line
    );
  }
};
```
Or break up the challenge into two parts.  One for an introduction to ES6 and the other to the React render function.

**Comment by bonham000** [comment]
Cool, I think this is a good point. I've updated it so you have to complete the rest of the render method now.
