### ISSUE TITLE
UI Positioning Suggestion: Change the Place of the Instructions and Tests

### ISSUE THREAD

**Issue by benschac** [bonham000/fcc-react-tests-module#155]
As a User, I continually have to scroll between the code, live preview and instructions.  When working on a problem the user has to scroll quite a bit.

<img width="1280" alt="screen shot 2017-01-16 at 5 51 07 pm" src="https://cloud.githubusercontent.com/assets/2502947/22002320/ff4fb460-dc18-11e6-9165-4d3fcf477c28.png">

**Comment by bonham000** [comment]
This is a good point and it's been brought up by others but because these challenges will eventually be merged into the FCC platform we're not going to revise the structure of this app for the time being.
