### ISSUE TITLE
Problem 13 -- Live Preview Shouldn't work if not rendering to the DOM

### ISSUE THREAD

**Issue by benschac** [bonham000/fcc-react-tests-module#156]
<img width="1280" alt="screen shot 2017-01-17 at 12 56 16 pm" src="https://cloud.githubusercontent.com/assets/2502947/22032979/a96f9032-dcb4-11e6-8e66-46f6271e4eb9.png">

**Comment by bonham000** [comment]
Cool! This is a good catch I've modified the live-render function for this challenge to only render the user's component if they've completed the ReactDOM statement.
