### ISSUE TITLE
React challenge 12 fails test

### ISSUE THREAD

**Issue by eeclaire** [bonham000/fcc-react-tests-module#157]
The code in the attached image fails test, even if indent is added before Fruits and Vegetable components to match solution code

![react12_bug](https://cloud.githubusercontent.com/assets/11424973/22034308/dd214d6c-dcb9-11e6-976b-aafbf1ee7b14.png)

**Comment by bonham000** [comment]
`Get` should be lowercase: `document.getElementById`

**Comment by eeclaire** [comment]
:+1:

**Comment by eeclaire** [comment]
But the Fruits and Vegetables components should be on the same indentation level as the h1 tag, right? Or does it not matter?

**Comment by bonham000** [comment]
Nope! tThe indentation doesn't matter at all. All of the JSX will be compiled down so it can be indented in any arbitrary way.
