### ISSUE TITLE
Problem 28: Syntax Highlighting

### ISSUE THREAD

**Issue by benschac** [bonham000/fcc-react-tests-module#159]
<img width="1270" alt="screen shot 2017-01-17 at 4 50 28 pm" src="https://cloud.githubusercontent.com/assets/2502947/22041544/498873f2-dcd5-11e6-938e-59675c56ee50.png">

decrement and reset aren't formatted correctly.

**Comment by bonham000** [comment]
Yes, seems to be the case when writing the methods as arrow functions. I'm not sure why that happens but it will have to do with how code-mirror is parsing the code and applying the CSS. Feel free to dive into that if you want to try to find a solution!

**Comment by benschac** [comment]
Yeah, I was looking through the readme.  I'm not 100% on how exactly you'd want to go about the PR process or any kind of contribution.

Maybe you could update the readme with stuff like.
- Do PR's need to be linked to issues.
- How to branch and name a PR request.
- Any other procedural / process you'd like to have for submitting code.

**Comment by bonham000** [comment]
So you can submit a PR in any way you don't have to create a feature branch or anything.

**Comment by benschac** [comment]
👍
