### ISSUE TITLE
React 08: Create A Component With React - Problem Submitting/Testing Code

### ISSUE THREAD

**Issue by JessiW** [bonham000/fcc-react-tests-module#160]
Hello,

I noticed on this challenge (React 08: Create a Component With React) - that the app would not test my code.  I had to get the solution - which was the same was what I was typing in - in order to get the app to say I'd passed all the tests.

- Jessi

**Comment by bonham000** [comment]
hmm.... are you sure it was typed exactly the same? If you think it was, my suggestion is to produce a screenshot here of the code that won't pass the tests so I can try and reproduce this.

**Comment by JessiW** [comment]
Hi 

Tried it again this morning & it worked. Must've had a mistake in there somewhere that I didn't catch yesterday!

My apologies    ;)

Jessi

**Comment by bonham000** [comment]
Ok no worries!
