### ISSUE TITLE
React 20: Using props with ...

### ISSUE THREAD

**Issue by sabrawer** [bonham000/fcc-react-tests-module#164]
AFAICT, my code is exactly like the solution code, but it does not pass the test. I checked this several times. Actually, in my code, a "}" was on a different line than the solution code (but still correct), but when I altered the style of the solution code (but not its correctness) the solution code still passed the test. This is what I had originally:

const Camper = (props) => {
  return(
    <p>{props.name}</p>
    )
  };
    Camper.defaultProps={name:'CamperBot'};
    Camper.propTypes={name:React.propTypes.string.isRequired};

**Comment by bonham000** [comment]
You need to include `props.name` within a `p` tag at least, or in a `p` in a `div` like in the solution, as noted in the test: 'The Camper component should contain a p element with only the text from the name prop'. 

Also, there actually is a difference between your code and the solution code. In `React.PropTypes.string.isRequired`, `PropTypes` is capitalized — not `propTypes`.
