### ISSUE TITLE
React 29: Create a Controlled Input

### ISSUE THREAD

**Issue by piotr-m-jurek** [bonham000/fcc-react-tests-module#165]
![react29](https://cloud.githubusercontent.com/assets/11314344/22371535/e0983baa-e497-11e6-980a-cf997a1b0c10.JPG)

Hi! I think you are missing the test checking the value of input. I assume that if the input has initial state, it should render to the DOM.

**Comment by bonham000** [comment]
Yes, you're right I think the tests were not quite right here. I've updated them would you mind checking this challenge again? I didn't add another test but just changed the current tests. I think they are now verifying the intended behavior correctly.

**Comment by piotr-m-jurek** [comment]
hi, the 29 task works great now, but is noticed similar situation in 30th
challenge. I don't know if it is necessary, but it passes.

cheers!

2017-01-27 20:44 GMT+01:00 Sean Smith <notifications@github.com>:

**Comment by bonham000** [comment]
Ok great! I've fixed that too now.
