### ISSUE TITLE
26

### ISSUE THREAD

**Issue by Vozf** [bonham000/fcc-react-tests-module#166]
```
class MyComponent extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
      message: 'Hello!'
    };
	}
	setMessage = () => {
    this.setState({
      message: "Goodbye!"
    })
  }

	render() {
  	return (
	    <div>
        <button onClick = {this.setMessage}>Click Me</button>
        <h1>{this.state.message}</h1>
	    </div>
    );
  }
};
```

This code fails,but if i change doble quotes to singles it succeeds

**Comment by bonham000** [comment]
Can you verify again that this is happening? Be sure to refresh the page again. I tried this code just now on challenge 26 and it passed the tests for me.

**Comment by Vozf** [comment]
Nope,still not passing 
![image](https://cloud.githubusercontent.com/assets/22998537/22387159/5ab88194-e4eb-11e6-8cf7-1440d520136a.png)

**Comment by bonham000** [comment]
Ok! I've found what it is and fixed it. Thanks for bringing this up!
