### ISSUE TITLE
React36: Manage...: Question: What's happening - part 1

### ISSUE THREAD

**Issue by sabrawer** [bonham000/fcc-react-tests-module#167]
I have two questions - this is the first. My code is below. When the code first runs, it outputs the following:

[Log] will receive   ---> (This is from componentWillReceiveProps)
[Log] {message: "first"}
[Log] {message: "TestMessage"}
[Log] Component is about to update...
[Log] component did update

My question: Where did "TestMessage" come from?
-------------------
My code:
``` javascript
componentWillReceiveProps(nextProps){
  console.log("will receive");
  console.log( this.props);
  console.log( nextProps);
}
  componentDidUpdate(){
    console.log("component did update");
  }

I also added a log to
changeMessage = () => {
    **console.log("change message");**
		this.setState({
			message: 'second'
		});
	}
```
My next question will be about the order of events, but maybe your response will answer it.

**Comment by bonham000** [comment]
Oh, so that message is actually coming in from the tests. We're setting the state on the component in a test and verifying the `h1` tag displays the current text from the component state. We might want to change that given that you may be looking at the console messages and get confused by that. What do you think?

And does that answer your other question?

**Comment by sabrawer** [comment]
It’s definitely confusing, especially as you recommend that we look at the console output.  

It would be OK if you mentioned in the notes that it was going to happen. 

My second question is quite a bit more general. I think I should open an issue as it may be of general interest.

If you don’t mind a little digression - I like to understand in some detail what is going on under the covers, and with JSX there are a lot of covers. I wrote a document introducing React without using JSX. I experimented a lot and decided to write it up. It just touches the surface - not nearly as complete or useful as these challenges - more of a compulsive approach. But there are things in there that I think might be useful at least for your notes. Would you mind taking a brief look at it? I think there may be some mistakes as well. You certainly don’t have to look.  Anyway, it’s here.

https://github.com/sabrawer/hello-world/tree/master <https://github.com/sabrawer/hello-world/tree/master>


Thanks

Steve

On Jan 27, 2017, at 2:32 PM, Sean Smith <notifications@github.com> wrote:

Oh, so that message is actually coming in from the tests. We're setting the state on the component in a test and verifying the h1 tag displays the current text from the component state. We might want to change that given that you may be looking at the console messages and get confused by that. What do you think?

And does that answer your other question?

**Comment by bonham000** [comment]
Ok! Firstly, about the challenge I've just removed the test that was causing this additional `console.log` because it's not essential to this challenge. Now you will just see the relevant messages in the console, I think that should fix it.

**Comment by sabrawer** [comment]
Probably a good idea - makes everything simpler.

On Jan 27, 2017, at 3:00 PM, Sean Smith <notifications@github.com> wrote:

Ok! Firstly, about the challenge I've just removed the test that was causing this additional console.log because it's not essential to this challenge. Now you will just see the relevant messages in the console, I think that sould fix it.

**Comment by bonham000** [comment]
Secondly, yeah your document looks good! I think a lot of people do get stuck on JSX when they are learning React and some pick it up more quickly. Because it's used so ubiquitously, we did choose to just introduce it and use all of the examples using JSX in these challenges, but I think having a more in-depth understanding of how React actually creates HTML elements from JSX is useful to have.
