### ISSUE TITLE
React36: Manage-Order of events (part 2)

### ISSUE THREAD

**Issue by sabrawer** [bonham000/fcc-react-tests-module#168]
I want to make sure I understand the order of events when this code runs. Here's what I think - please tell me how wrong this is. Also, my terminology may be a little strange - I'm not sure what to call things.

When the button is pressed, the message property of the state object of Controller is modified and, as a side effect, this triggers a new rendering of all 4 elements in the render() method of Controller. In particular, this perhaps causes something like the function call:  
React.createElement(Dialog,{message: "second"},null); 
(but probably not this particular function???). Whatever the actual function is, it does not instantiate a new Dialog object (because I tested that the constructor is not called). Rather, this creates a brand new javascript object in memory representing Dialog (but not a new Dialog instance), which has a "props" that is a different object from the previous one (ie, at a new address in memory).  Then this new props is passed to the (already existing) Dialog instance , where it first shows up as nextProps and then as props. So this chain of events does not modify the old props, but replaces it.

The reason I'm going through all this is that I understand that props is supposed to be treated by the program as immutable, and therefore the previous props (in the "old" Dialog javascript object) must be replaced with the new one, and this new one is passed to the (already existing) Dialog object and becomes nextProps and then props.

Also, presumably this is why, in a further challenge, you compare nextProps props using (!==) and not checking the property value. **That may be confusing.**

I hope this is clear.

I'm not sure what's going on on cmd-enter (I use a mac). It seems to run the code twice, calling both constructors both times. There is something strange happening there, because under the button is "second".

Thank you.

**Comment by bonham000** [comment]
So, this is really digging into how React actually works. For that, you should consult the documentation fro a deeper understanding because I am definitely not an expert on the inner-workings of React. However, in general, my understanding is that React keeps a virtual DOM in memory of your current app structure. When a change occurs (a state update occurs), React will compute the next representation of the DOM as a result of this change in memory. It will then create a diff of these two representations to determine exactly what actually needs to be changed, and only then will it go into the actual DOM and make these changes. After a component is initially mounted to the page (that is when the constructor would be called), all further changes will occur in the way I just described. One of React's advantages is that all of that logic is abstracted away from the user.

I'm not sure what you mean about `nextProps` and `!==` in a future challenge. If you think there is something confusing there let me know which challenge you are talking about.

Also, `cmd-enter` is running the tests on your code. If you're looking at your `console` a lot to try to understand what is going on, I would recommend that because of the way we are testing the code you may be seeing output there that isn't necessarily a result of your code. If you are trying to really inspect how React works in that way I would suggest just writing some React code in a different environment.

**Comment by sabrawer** [comment]
In React 37 you have (note !==)

If you wrote return nextProps !== this.props the component would only update when it receives new props that are not equal to the current props.

Is there a challenge where the application, on a button click say, changes the number of elements in a component?  For example, a list where the number of list elements can vary.

Thanks for your responses

Steve




On Jan 27, 2017, at 3:36 PM, Sean Smith <notifications@github.com> wrote:

So, this is really digging into how React actually works. For that, you should consult the documentation fro a deeper understanding because I am definitely not an expert on the inner-workings of React. However, in general, my understanding is that React keeps a virtual DOM in memory of your current app structure. When a change occurs (a state update occurs), React will compute the next representation of the DOM as a result of this change in memory. It will then create a diff of these two representations to determine exactly what actually needs to be changed, and only then will it go into the actual DOM and make these changes. After a component is initially mounted to the page (that is when the constructor would be called), all further changes will occur in the way I just described. One of React's advantages is that all of that logic is abstracted away from the user.

I'm not sure what you mean about nextProps and !== in a future challenge. If you think there is something confusing there let me know which challenge you are talking about.

Also, cmd-enter is running the tests on your code. If you're looking at your console a lot to try to understand what is going on, I would recommend that because of the way we are testing the code you may be seeing output there that isn't necessarily a result of your code. If you are trying to really inspect how React works in that way I would suggest just writing some React code in a different environment.

**Comment by bonham000** [comment]
Yes that's exactly right. If the `props` is a `string` or `number` then that is what will happen. If it was an object or array it would not be as simply as just comparing them with `!==` but the notion of 'If the next props are the same as the current props, don't re-render' is the core idea. I think I will update how that reads so it's more clear.

I don't think there are any challenges at the moment where the number of items in a list changes, but the challenges where you `map` items in a list out would be easy to add a button that removes elements from the list to achieve that.

**Comment by sabrawer** [comment]
In thinking about this, you might spend a little more time in the beginning on the origin of props and its structure in relation to the inline attributes. 

On Jan 27, 2017, at 3:36 PM, Sean Smith <notifications@github.com> wrote:

So, this is really digging into how React actually works. For that, you should consult the documentation fro a deeper understanding because I am definitely not an expert on the inner-workings of React. However, in general, my understanding is that React keeps a virtual DOM in memory of your current app structure. When a change occurs (a state update occurs), React will compute the next representation of the DOM as a result of this change in memory. It will then create a diff of these two representations to determine exactly what actually needs to be changed, and only then will it go into the actual DOM and make these changes. After a component is initially mounted to the page (that is when the constructor would be called), all further changes will occur in the way I just described. One of React's advantages is that all of that logic is abstracted away from the user.

I'm not sure what you mean about nextProps and !== in a future challenge. If you think there is something confusing there let me know which challenge you are talking about.

Also, cmd-enter is running the tests on your code. If you're looking at your console a lot to try to understand what is going on, I would recommend that because of the way we are testing the code you may be seeing output there that isn't necessarily a result of your code. If you are trying to really inspect how React works in that way I would suggest just writing some React code in a different environment.

**Comment by sabrawer** [comment]
Thanks, I’ll look for that.

On Jan 27, 2017, at 4:18 PM, Sean Smith <notifications@github.com> wrote:

Yes that's exactly right. If the props is a string or number then that is what will happen. If it was an object or array it would not be as simply as just comparing them with !== but the notion of 'If the next props are the same as the current props, don't re-render' is the core idea. I think I will update how that reads so it's more clear.

I don't think there are any challenges at the moment where the number of items in a list changes, but the challenges where you map items in a list out would be easy to add a button that removes elements from the list to achieve that.
