### ISSUE TITLE
Finished React challenges. How to use JSX outside of CodePen?

### ISSUE THREAD

**Issue by sabrawer** [bonham000/fcc-react-tests-module#169]
This is a wonderful tutorial - clear, focused and I am sure very useful when I get started tomorrow. Obviously a lot of thought went into this, for topics covered, sequence of challenges ,and the explanations. 

Two final questions:  (1) Away from the CodePen environment, do I need a ReactDOM.render() function to actually draw something, or does JSX take care of that? (Probably JSX, but I thought I'ld ask.)  (2)  I will go with JSX after being enlightened here. What is the best way of using Babel in my local environment (where I do all my coding)? Is there a CDN, or a downloadable executable which I have to reference or import into the browser? Are there two files involved (like SCSS)? What option do you recommend for creating the React challenges in FCC? (You might mention this somewhere in the tutorial.)

Thanks again for this brilliant tutorial.

**Comment by bonham000** [comment]
So the final challenge in this series (React-Redux 10) makes some suggestions about moving forward and working with React in a different environment. You do have to have react, react-dom, and babel all available but how this is done will vary depending on your setup. In Codepen babel can be enabled as a pre-processor and the react libraries included as dependencies. That's a pretty easy way to get started. Create React App which is the advice in given in this tutorial is also a very good way.
