### ISSUE TITLE
QA: General Feedback

### ISSUE THREAD

**Issue by bonham000** [bonham000/fcc-react-tests-module#17]
This Issue is the place to discuss any general feedback on these challenges.

**Comment by alayek** [comment]
One of my pet peeve was the gazillions of live rendering errors in console. I hope this would go away in the main site, right?

Otherwise, students would have a hard time trying out some snippets in browser console, while working on these.

**Comment by bonham000** [comment]
Yeah I agree and yes we could remove these here but I've left them because they have helped us developing and debugging some of the challenges. They shouldn't be in the final version.

**Comment by dhcodes** [comment]
`cmd + enter` to submit a challenge seems a bit 'Mac-centric' since windows and linux machines don't usually have a cmd key. Should we list an alternative for other OS?

**Comment by bonham000** [comment]
Let me take a look at implementing `ctrl + enter` for non-Mac machines as a way to test the challenge code if that is a good key combination for this?

**Comment by dhcodes** [comment]
I think that's what FCC uses per this thread https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9850

**Comment by bonham000** [comment]
Okay I'm going to go ahead and add this. Should be available in the next few minutes.

**Comment by ghost** [comment]
I think we should have the Live Preview below the code, rather than above. When the live preview updates, it's easy to lose track of where you are in your code.

**Comment by PorgJuice** [comment]
Since I've only been posting issues about the problems I've found, I'd like to say that this has been one of the best introductions to React that I've ever seen.  This is a fantastic course that's going to help a lot of people.

**Comment by ethanrose** [comment]
I started from Redux 1, and I'm on lesson 12 now.. It's super awesome and clear, and I'm learning a lot! Thank you. I'm just making pull requests for typos -- everything seems to be working perfectly for me so far.

**Comment by ethanrose** [comment]
So in redux lesson 13, none of the tests seem to be working, even the console output doesn't show anything when I `console.log()` it's the "write a counter in redux" - here's my code

```
const INCREMENT = 'plus';
const DECREMENT = 'minus';

const counterReducer = (state = 0, action)=>{
	switch(action.type){
    case INCREMENT:
      return state + 1;
    case DECREMENT:
      return state - 1;
    default:
      return state;
}
  
const incAction = {type: INCREMENT}

const decAction = {type: DECREMENT}
  
const store = Redux.createStore(counterReducer)
  
console.log('test')
```

**Comment by bonham000** [comment]
I think it's probably functioning correctly. There needs to be a closing bracket `}` to end the `switch` statement and both action creators `incAction` and `decAction` have to be functions that return objects with a `type` property. Otherwise, this code looks good and passes when I test it with those modifications.

**Comment by ethanrose** [comment]
Ah my bad! You're right, that works.

**Comment by bonham000** [comment]
No worries! By the way thanks a ton for working on the Redux challenges and sending in that PR. I'm about to merge it. Haven't gotten a ton of feedback on the Redux challenges yet so I'm glad to hear you like them. 👍

**Comment by tommygebru** [comment]
Update css stylesheet to include this declaration
`body{width:100vw;}`

**Comment by bonham000** [comment]
What issue are you seeing with the width?

**Comment by tommygebru** [comment]
Fix a typo,
"consecutively"

**Comment by BWilkey** [comment]
I just wanted to thank you for your work on this.  I've been looking forward to working on React, and these challenges are great.  I've only made it through the first 24 so far, but I'll keep going and send in any thoughts.

**Comment by bonham000** [comment]
Awesome! Thanks a lot for your feedback it's really helpful!

**Comment by bonham000** [comment]
I've updated the code with the recent changes you've suggested but it won't show up in the live version immediately, FYI.

**Comment by tommygebru** [comment]
No worries the experience is pretty awesome so far

**Comment by jneums** [comment]
In number 28 only the first two functions are shown as green in the editor, and the following ones are white which might be confusing because that could mean there is a syntax error that is keeping them from being seen as functions.

**Comment by bonham000** [comment]
I agree and an issue like this was brought up previously. It probably is due to the way the code editor component is trying to syntax highlight JSX... I'll keep on an eye on this and if it is still an issue once the challenges are merged into the core FCC curriculum we may try to look into it more closely and fix it.

**Comment by jneums** [comment]
I found another small thing, I hope its not being to nit-picky. 
In React 43 the code editor has a comment // change code below this  line in the parent component, but when I did the exercise and then when I looked at the solution, the code below that line was the same. Could be confusing I think.

**Comment by bonham000** [comment]
You're right about that, that's a good thing to fix. I've just changed it, thanks!

**Comment by jneums** [comment]
On React 46, it says put "Eat, Code, Sleep, Repeat" into the input field, but anytime you push Shift+S it changes the code to the Solution Code.

edit: just realized this does not matter because when it is on freecodecamp.com it will not have the solution.

**Comment by bonham000** [comment]
Yes, that's because we made that a shortcut key to load the solution code... So it will get in the way if you are trying to type a capital S with the shift key. This was mainly for use when we were developing this so it won't be included in the final version. Shift R reloads the seed code.

**Comment by juandaco** [comment]
Hi. Thank you for your work on this .
I found a very minor spelling issue in React 07. In Instructions the `myComponent` starts with minuscule when it should be `MyComponent`.

**Comment by bonham000** [comment]
@juandaco thanks! Got it changed.

**Comment by jneums** [comment]
Just found another really minor thing that would be fine as is, but would be more consistent if it were changed. On React/Redux 03 it says to call the reducer "messageReducer()" but in the comments it says to create "reducer()". The only reason I bring it up is because the test is looking for a specific function name.

I also wanted to say how excited I am to get to work through these challenges, you have done a really great job! By far the most valuable React/Redux learning resource I have seen, and I spent a lot of time looking at so many tutorials. Thank you!

**Comment by bonham000** [comment]
Ok, @Jesse989 that's a good point and I've fixed it now. And thanks for the positive comments!

**Comment by dgrcode** [comment]
Hi guys, I want to thank you for all the work and effort put together to create this awesome learning material. I'm going through the challenges and so far reached number 8. I currently know some React that I had to learn in other tutorials over the internet, but I'll do them all to give some feedback. I will join the people saying that this is the best material to learn react that I've found on the internet so far. As a bonus I will learn Redux here, that I haven't learn yet :smiley:

I have found a bit confusing one sentence at challenge 2. I must say that English is not my mother tongue, and that could be the reason behind my confusion. The intro says (italics for the confusing sentence):

> Intro: The last challenge was a simple example of JSX, but it can include complex nested HTML as well. One important thing to know about nested JSX is that it ultimately needs to return only one outer element. This single parent element would wrap all of the other levels of nested elements. *The JSX will not transpile if, for example, your code has several elements that are siblings, but no parent element wrapping all of them*. Here's an example:

I would use there something more straight like: *The JSX will not transpile if there are more than one element at the root level, without a parent element wrapping all of them*. For me, the "for example" bit was the confusing part, but as I said it might be just the way I understood it.

I'll keep writing here any feedback that I have. And thank you for your work again :clap:

**Comment by bonham000** [comment]
Great, thanks @dgrcode! I just made some edits to that challenge. If you have any more feedback later on feel free to open another Issue specifically for that challenge, thank you!

**Comment by dgrcode** [comment]
I've seen the edits. Crystal clear now!
Just to mention that there's a small misspelling on the edit: "... will not _transpil**t**e_"

**Comment by bonham000** [comment]
Oh, oops someone submitted a PR for that a few days ago but I hadn't updated it yet. I have now, it should all be correct!

**Comment by Y-Taras** [comment]
in Firefox buttons do not look as it should.

**Comment by bonham000** [comment]
@Y-Taras, you're thanks for noticing. I just adjusted the CSS to fix this.

**Comment by jayullman** [comment]
I just finished all of the React challenges (1-48). After trying several different React tutorials from various sources, this is the one that really solidified a lot of the confusing pieces for me. Thanks for all of your hard work on this!

**Comment by bonham000** [comment]
@libeja thanks for your comments! I really appreciate the feedback. I hope you continue through to the Redux challenges as well. Although these are shorter than the React challenges we've gotten much less feedback on these so I'm really keen to hear what people think about them. Thanks again!

**Comment by AdventureBear** [comment]
I am a React newbie and couldn't even tackle this until i'd familiarized myself with React somewhat. I'm 4 hours into a front end masters React course as my first exposure.   Looking at these challenges I am incredibly impressed with the work that has gone into it.   

My initial feedback is that the jump from challenge 7 to challenge 8 seems huge to me...it's about 3 new concepts added at once (super class, props, Kittens, what?).   challenges 1-7 seem pretty straightforward for a newbie so far.

**Comment by dhcodes** [comment]
Below is my general feedback so far. Forgive me if any of these have been said already. Should I make new issues regarding my suggestions for individual challenges or post those here as well? 

General Feedback:
So far, as many have said I think this is the best React tutorial out right now. I love the attention to detail and your desire to cover everything. 

1. I'm sure someone has mentioned this, but the page is not responsive and FCC has a lot of campers who use mobile devices to do challenges.

2. Pages should jump back to top when new challenge is loaded. I know there is some debate on this for users who want to only do the challenges based on the tests, but I would guess the vast majority of users want to read the intro, which currently requires scrolling up on load of each new challenge.

3. I would change the 'Reload Seed' button to 'Reset Code' to keep a similar naming practice to FCC.

4. Consider side-by-side editor/renderer view so page does not move as changes are made.

5. Add linting to the editor as a typo will prevent tests from running with no indication of what's wrong.

6. Hitting the "back" button on the browser will dump you out of the challenges. Would React router help remedy this?

7. You might consider using a side-by-side approach like the FCC challenges do or move the rendered view below the editor. The reasoning is that as the renderer changes, the editor shifts down the screen as a result.

8. If you `Ctrl + Z` or Undo too many times, it will start bringing in code from past challenges.

9. Is it possible to have the new lines in the editor be pre-indented for where the code should go? This is a silly nitpick but would save some effort for the user and promote code readability.

**Comment by bonham000** [comment]
@dhcodes these are all great points and observations! Thanks for your comments. For the time being, because the goal is for all of this content to be ported into the FCC platform when the QA process is finished, I think it's safe to leave most of these issues unaddressed in the app running on Surge. If any of these are still a concern once the material has been moved into FCC we can definitely revisit it.

**Comment by dhcodes** [comment]
Guess I should read better ☺️. Didn't realize they'd be ported over.

**Comment by bonham000** [comment]
No worries!

**Comment by HKuz** [comment]
@bonham000 and others - here's a point for discussion for maybe adding a new challenge. I noticed in React challenge 46 `Use Array.map() to Dynamically Render Elements`, the solution added a key to each list item generated by the map callback. It wasn't required to pass the tests, so I didn't think it was worth adding more explanation to that challenge. That said, is this topic (making sure dynamically rendered elements have unique ids so React can track them) worth adding a challenge to cover? 

If so, I think we can just re-use a lot of React-46. I can draft up the challenge text, we can use the same example and code but just have the camper include a key, and add one more test to check for keys on the li's. Then we just need to think of one more challenge to make React an even 50 (just kidding 😄).

**Comment by bonham000** [comment]
Actually, yes @HKuz this topic is pretty important and should definitely be included. I thought we had mentioned somewhere about the need to add unique a `key` for sibling child elements but having looked through the challenges just now it looks like we did not... maybe it was removed somewhere.

Because this is a pretty important thing to include and because Challenge 46 is already so long, I think we should create a Challenge 47 specifically to deal with this. It can be as simple as explaining why we need to create a unique `key` and then having the user add a unique `key` attribute to a some data that we are already mapping over. What do you think? If you want to try and write this, that would be great!

And believe me... I'd love to get up to that big **50**.

I've just updated the [challenge map](https://github.com/bonham000/fcc-react-tests-module/blob/master/CHALLENGE_MAP.md) to reflect this... let me see if I can find any gaps for a 50th challenge. We could add a challenge in the **advanced rendering** section, maybe after 45, that has you change CSS conditionally, as this is something I've used before and it's not really covered elsewhere. Let me know what you think about this, at the moment no other React topics are coming to mind that we could possibly add.

**Comment by HKuz** [comment]
Sounds like a plan, @bonham000 - I'll take a shot drafting the new challenge, and will include what you mentioned. 

As for that elusive 50th challenge, I'll try to think of anything, too. A challenge on conditional CSS could be a good one!

**Comment by bonham000** [comment]
Ok @HKuz we will keep thinking about **50**. For now, feel free to go ahead and create **47**, you can add the new file and modify `App.js` to import it in the app but you'll have to modify the file names after it. If you feel comfortable with all that go ahead! Otherwise, you could just create the file and give it some other name for now, e.g. `Draft_48.js`.

**Comment by HKuz** [comment]
Okay, thanks for the head's up - I'll give it a shot and will hit you up on Gitter if I run into any issues.

**Comment by sabrawer** [comment]
Please see these links to the forum, where I put my initial comments. This is a wonderful tutorial - the best out there that I have seen.

https://forum.freecodecamp.com/t/react-tutorial-on-code-pen/74662
https://forum.freecodecamp.com/t/react-tutorial-cokmments-lessons-4-7/74678/3

**Comment by nickpapasavvas** [comment]
Hello guys and congratulations for the awesome work. I don't know if this is how React works or it is a minor bug but in React Challenge 20 if you give to the key name the value CamperBot inside double quotes  like this {name:"CamperBot"} you get an error on the fourth test. So to pass the test the only acceptable is {name:'CamperBot'} (single quotes).

**Comment by bonham000** [comment]
@nickolaos77 you're right about that! I've just changed it. It's hard to actually test for prop types. If you catch anything else like this, please let us know.

**Comment by nickolaos77** [comment]
Hello so in react challenge 26 the correct solution for the arrow function is this  :            `setMessage = () => {
		this.setState({
			message: 'Goodbye!'
		});`

Shouldn't the function be declared with const in front of its name : const  setMessage

**Comment by nickpapasavvas** [comment]
Hello guys I have noticed a problem with React-Redux 07 . When we try to solve the challenge the last render method is wrong (returns only a  `<div/>`
) so no text appears in the live preview window. However the solution code is correct and returns `<h3>This is a Presentational Component</h3>`

**Comment by bonham000** [comment]
@nickolaos77 nice job finding that! I just fixed it. Thanks!

**Comment by nickpapasavvas** [comment]
Sean one thing I also noticed some tags that are like this <div><div/> is
this correct ? Or the only correct is this <div></div>?

2017-02-02 18:19 GMT+02:00 Sean Smith <notifications@github.com>:

**Comment by bonham000** [comment]
@nickolaos77 no, they should be `<div></div>`. If you see any not like this could you make a note of them here? I will try to glance through the challenges today and see if I can find any like that.

**Comment by nickpapasavvas** [comment]
I had found one and wrote it on the issues but nobody replied and I thought
it t was valid react syntax so I erased it. I will go and find it now

2017-02-02 18:37 GMT+02:00 Sean Smith <notifications@github.com>:

**Comment by bonham000** [comment]
@nickolaos77 yes please try to find! I've been trying to respond to all issues before closing them, if you can find the issue feel free to reopen it!

**Comment by nickpapasavvas** [comment]
I found it it is in the example code of React-redux 04 the <Provider/> tag.



2017-02-02 18:44 GMT+02:00 Sean Smith <notifications@github.com>:

**Comment by bonham000** [comment]
@nickolaos77 thanks for finding that, I just fixed it. I'm sorry if I missed this in an issue previously!

**Comment by nickpapasavvas** [comment]
Congratulations for the great work Sean, I have already done these
exercises a couple of times and I plan to repeat them often so React and
Redux sink in to me!!  Your work will improve us all!!

2017-02-02 20:06 GMT+02:00 Sean Smith <notifications@github.com>:

**Comment by Greenheart** [comment]
I agree with @dhcodes https://github.com/bonham000/fcc-react-tests-module/issues/17#issuecomment-269990048
> Is it possible to have the new lines in the editor be pre-indented for where the code should go? This is a silly nitpick but would save some effort for the user and promote code readability.

Something I thought about for several challenges.

**Comment by Ethan-Arrowood** [comment]
@bonham000 I am interested in helping migrating these challenges to the actual FCC Beta site. How can I get involved? (FYI I am already familiar with React, Redux, and as of recently FCC core challenge-saga)

**Comment by nickpapasavvas** [comment]
One thing that remains unclarified for me at least after going through all the challenges is why inside a React component functions are declared as
`hello(){ ... }` and not as `function hello(){...}` also why an arrow function declared as for example the following one (function from lesson 41) doesn't work and webpack throws syntax error          `	toggleDisplay = () => {
		this.setState({
			display: !this.state.display
		});
	}`

**Comment by Ethan-Arrowood** [comment]
@nickolaos77 when you are declaring 'functions' inside a React Component you're actually defining methods (similar to defining methods of a Java or C#/++ object). The notation is confusing because JavaScript is not traditionally a OOP language but with React it almost is. 
In regards to you the arrow function maybe try removing the semicolon?

**Comment by nickpapasavvas** [comment]
@Ethan-Arrowood I tried different syntaxes for the arrow functions but I get an error no matter what, the syntax previously was from the react challenges and for example also the following throws an error of type Unexpected token pointing at the equal sign 'hello = ()=>{console.log("hello")} ' also the syntax with `const hello` throws error

**Comment by Ethan-Arrowood** [comment]
Can you send a screenshot of the webpack error?

**Comment by bonham000** [comment]
@nickolaos77 I can't respond in depth right now but see the note we made in the instructions to Challenge 26 and this (possibly the answer).

**Comment by nickpapasavvas** [comment]
@Ethan-Arrowood 
![image](https://cloud.githubusercontent.com/assets/14972276/23717608/2832e2de-043d-11e7-8af0-3c2a9da4992d.png)
@bonham000 Yes I remember reading this note but I  do use preprocessor (webpack). Anyway I am ok with the normal functions but I just observed it and thought it would be nice to inform you

**Comment by Ethan-Arrowood** [comment]
@nickolaos77 your issue is what we discussed before regarding react component methods. These are not the same as traditional JavaScript function syntax.

**Comment by nickpapasavvas** [comment]
@Ethan-Arrowood which would be the correct syntax for this arrow function?

**Comment by bonham000** [comment]
@nickolaos77  yes so I'm pretty confident this is the problem referenced in Challenge 26, namely that writing ES6 class methods as arrow functions is not supported in ES6 and is a futuristic ES7 feature which you must enable specifically, e.g. `babel-preset-stage-2`, so please take a look at that note more carefully to see what's going on here.

Otherwise, you can just write the methods as regular functions and `.bind(this)` in the `constructor` if you need to do that.

**Comment by bonham000** [comment]
@Ethan-Arrowood thanks for your interest in helping migrate these to FCC Beta! At the moment, I have not heard anything about this migration from the other core team members, so for now these challenges will probably continue living here (which is fine, because this is a very efficient way for issues/bugs to handle, which still are arising occasionally, before the official merge). The main problem is the testing process for these React/Redux challenges needs to be recreated on the FCC platform before the challenges can be ported over and this hasn't been done yet.

However, once that transition is happening if more help is needed I will try to message you!

**Comment by Ethan-Arrowood** [comment]
@bonham000 Wonderful! ~Which testing suite are you using? Is it karma/mocha?~ Looks like Enzyme and Jest. Still, I'd be interested in working on integrating it into the FCC core. Hmm. Maybe I'll give it a shot, wouldn't hurt to try.

**Comment by bonham000** [comment]
@Ethan-Arrowood So in this project the testing process is roughly:

1. string of code from browser code editor may have short scripts added to it
2. code is processed with babel (sometimes with different presets)
3. code is `eval`ed and passed to `React.createElement` (for React challenges)
4. A mock component is created using Enzyme's `shallow` or `mount` method
5. specific tests are run against this component using the node `assert` module

The aggregated test results are returned to the UI.

This process looks a little different depending on the type of challenge (e.g. Redux challenges mostly don't use `React.createElement`).

So one issue is that the testing is not totally consistent throughout all of the challenges. Another issue is that pretty much the only commonality between the above and the current FCC challenges is the use of node `assert` library...

But that's the gist of it. Of course, all the code responsible for the testing is in the repo here, and you can get a sense of the process by looking at the challenge files. Likewise in FCC.

This is definitely going to be the final hurdle to overcome for the integration of these challenges into the FCC codebase, and I bet help will be needed solving this testing problem, so if you're interested please give it a shot.

[Here is the FCC issue presumably responsible for this](https://github.com/freeCodeCamp/freeCodeCamp/issues/13326) and BerkeleyTrue is the one who will likely end up working on at least part of this. Feel free to post in that issue as well.

**Comment by Ethan-Arrowood** [comment]
We will have to transpose these challenges into the FCC Core challenge seed JSON format correct?

**Comment by bonham000** [comment]
I don't know for sure, but likely the end result (ideally) would be having the content of these challenges (text, seed, solution, tests) living in JSON files (so, essentially like the other challenges). However, this probably means the actual code responsible for loading these challenges and processing the tests will need to be different than the current code responsible for testing the JS challenges (to support use of Enzyme, babel-standalone, React, etc).

So this would require some different testing components for these challenges which presumably the challenges JSON files would indicate they need.

**Comment by Ethan-Arrowood** [comment]
Mhm okay well this is definitely a big challenge! Let me know if there are ever any other (smaller) issues I can lend a hand with. Really would love to get into some true issue fixing instead of just fixing typos 😝

**Comment by bonham000** [comment]
Yeah totally — and yes this isn't a trivial challenge which is why basically everything has been finished  but this last obstacle.

Depending on your interest in advanced data structures and algorithms, I know those challenges (in Beta) need some more work (beyond mere typo/grammar/language correction).

[FCC Issue on these](https://github.com/freeCodeCamp/freeCodeCamp/issues/12757)

**Comment by Ethan-Arrowood** [comment]
Oooh perfect! Thank you!

**Comment by nickpapasavvas** [comment]
@bonham000 so to be able to use the arrow functions this way I should npm install babel-preset-stage-2 and then modify my  webpack like this `presets:['react','es2015', 'es7']` , adding es7? Is this how I can use arrow functions as class methods?

**Comment by bonham000** [comment]
@nickolaos77 Yes, in `webpack.config` or in `.babelrc`, wherever you are setting up the babel presets, and I think the preset itself is `stage-2`.

I (think) if you use Creat-React-App this will be enabled out of the box.

**Comment by ccrubby214** [comment]
@bonham000 , I have to say , it's awesome React tutorial for me, clear and definite！ but I had met a problem about dynamic rendring, when I finished the challenge and clicked the 'test code', nothing to feedback to me, no error infos or any other things. Opened the dev tools, it will show the infos such as"Live rendering failed ReferenceError: React is not defined"  and I checked my answer with the 'solution code', it's just the same. So I don't know whether my brower's(Chrome 56.0.2924.87)problem or my operation mistake. Hope your reply, it's really a good curriculum for me. : )

**Comment by bonham000** [comment]
@ccrubby214 I would recommend reloading the page in the browser and attempting the solution again. Anything different? If you are certain your code is correct (the same as the solution code) please open a new issue here and include your code so we can investigate further. Thanks, and I'm glad you like the challenges!

**Comment by nickpapasavvas** [comment]
@bonham000  Yes this is how it is done 1. `npm install babel-preset-stage-2` and the add `stage-2` to the array on the presets inside webpack.config.js

**Comment by ccrubby214** [comment]
@bonham000 thanks first, I found the key point is not that I mentioned before, becasue I found that when I typed my code in 'code panel',  there is nothing showed in 'Live Preview', whatever I typed in, and I tried it in different browers, such as chrome, chrome canary, IE11, Microsoft Edge, I got the same result-nothing to show in 'Live Preview', Maybe you won't provide the 'Live Preview'? I don't know, if it's my operation mistake, pls tell me and I still want to learn your Curriculum with a better experience, thanks a ton!

**Comment by bonham000** [comment]
@ccrubby214 which challenge number is it? There should be something previewed in the Live Preview panel and if not at minimum all the tests should move from failed to passing (if the solution is correct). At this point we've had a lot of user testing on these challenges so I'm pretty confident they are working as expected.

Again my advice would be to double check your code matches the solution and refresh the browser beforehand just in case.

**Comment by bonham000** [comment]
This is getting too long will close and open a new one.
