### ISSUE TITLE
Redux 10

### ISSUE THREAD

**Issue by Vozf** [bonham000/fcc-react-tests-module#172]
I think this paragraph needs rewriting. I'm a non-native speaker and with this one I can't really understand what it means.It started to make sense only after I opened the solution and even now I don't understand the last sentence.Even though I practically had no problems with all the previous ones
`Redux provides the method combineReducers() for this purpose. The combineReducers() method is available on the Redux object. You pass the method an object as an argument, and in that object, reducers are mapped to property names. The names of these properties become the names of the keys in the state object for the state managed by that reducer. `
Is it like there are several states in one big state?Not really clear
It should at least contain an example.Something like the first example here http://redux.js.org/docs/recipes/reducers/UsingCombineReducers.html

**Comment by bonham000** [comment]
Yes, I can see how that can be unclear. What do you think about the following:

> In order to let us combine multiple reducers together, Redux provides the `combineReducers()` method. This method accepts an object as an argument in which you define properties which associate keys to specific reducer functions. The name you give to the keys will be used by Redux as the name for the associated piece of state.

> Typically, it is a good practice to create a reducer for each piece of application state when they are distinct or unique in some way. For example, in a note-taking app with user authentication, one reducer could handle authentication while another handles the text and notes that the user is submitting. For such an application, we might write the `combineReducers()` method like this:

``` javascript
const rootReducer = Redux.combineReducers({
   auth: authenticationReducer,
   notes: notesReducer
});
```

> Now, the key `notes` will contain all of the state associated with our notes and handled by our `notesReducer`. This is how multiple reducers can be composed to manage more complex application state.

**Comment by Vozf** [comment]
To my mind it should be noted that previously with the getState we got just the state and now we got an object with keys as we sent to combineReducers associated with different states
This might not be true it's what I understood from searching the web

**Comment by bonham000** [comment]
Yes, that is true. If your state is just a `number` or `string`, then that's your state. If you have more complex state like here, then it's still one thing, but now it's stored as an `object` which contains the different pieces of state as key-value pairs. Either way, calling the method `getState` just returns whatever the state is / how it is represented.

**Comment by Vozf** [comment]
This is worth mentioning.Previously we had 1 state and it can be not clear what is going on when there is more

**Comment by bonham000** [comment]
Well so the thing is there is still just 1 state. Previously it was a string, or number, now it is an object. Then within that object state is organized into different pieces. I'm going to re-write the text in this challenge to try and make these points more clear.

**Comment by Vozf** [comment]
Ok,thanks
