### ISSUE TITLE
React 30 - There's no test for h1 tag content.

### ISSUE THREAD

**Issue by zelite** [bonham000/fcc-react-tests-module#176]
On the challenge React 30 - Create a Controlled Form, the last line of the challenge says:

> Finally, create an h1 tag below the button which renders the submit value from the component's state. You can type in the form and click the button, and you should see your input rendered to the page.

The tests only test for the existence of the h1 tag, but do not test for the rendering of the submit value. My code below passes the tests, even though I do not have anything inside the h1 tag.

```
class MyForm extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			input: '',
			submit: ''
		};
	}
	handleChange = (event) => {
		this.setState({
			input: event.target.value
		});
	}
	// change code below this line
	handleSubmit = (event) => {
  	this.setState({
      submit: this.state.input
    });
  }
	// change code above this line
	render() {
  	return (
	    <div>
        { /* change code below this line */ }
        <input onChange={this.handleChange} value={this.state.input}></input>
        <button onClick={this.handleSubmit}>Submit</button>
        <h1></h1>
        { /* change code above this line */ }
	    </div>
    );
  }
};
```

**Comment by bonham000** [comment]
Ok great! There actually wasn't a test for that, it was just mentioned in the instructions so I think this was a good thing to discover. I've just added a test specifically for this.

It'll be a minute before it's updated live as I'm going through all the issues you just posted.

Thanks for finding this!
