### ISSUE TITLE
React 40 - text description is wrong about ask() method

### ISSUE THREAD

**Issue by zelite** [bonham000/fcc-react-tests-module#178]
On the challenge React 40: Use Advanced JavaScript in React Render Method, the challenge descriptions says:

> The button click event is bound to the ask method, so each time the button is clicked, a random number between **1 and 20** is stored in the component's state object.

The ask method is this:

```
	ask() {
		if (this.state.userInput) {
			this.setState({
				randomIndex: Math.floor(Math.random() * 20),
				userInput: ''
			});
		}
	}
```

This method creates an integer between 0 and 19, and not between 1 and 20. The text description should be updated.

**Comment by bonham000** [comment]
I've just fixed this.

**Comment by zelite** [comment]
Hi,

I noticed that you changed the code for the ask method. Now the method generates indeed a index between 1 and 20.
However, I think this is incorrect.  The code should really generate the index between 0 and 19, because arrays in javascript are zero indexed and the `possibleAnswers` array has a length of 20. What should been changed was the description of the challenge and not the code.

**Comment by bonham000** [comment]
Ok I see what you mean! I've updated the instructions now.
