### ISSUE TITLE
React04: Render HTML Elements to the DOM typo on test case

### ISSUE THREAD

**Issue by ghost** [bonham000/fcc-react-tests-module#18]
Possible typo for a test case of the challenge `Render HTML Elements to the DOM` as shown in the highlighted text below:

#### Test Cases:

- Your JSX code was transpiled successfully.
- The constant JSX returns an <div> element.
- The div contains an h1 tag as the **second** element.
- The div contains an p tag as the second element.
- The provided JSX element is rendered to the DOM node with id 'challenge-node'.

I think it should be `first` instead of `second`?

**Comment by bonham000** [comment]
Yep, nice catch! I'll fix that and it will be corrected next time this is updated. Thanks!
