### ISSUE TITLE
Improve tests for "Learn About Self-Closing JSX Tags"

### ISSUE THREAD

**Issue by Greenheart** [bonham000/fcc-react-tests-module#181]
Currently, the tests are very strict about formatting - they fail even if a space if removed or a line break is added.

Space removed
![improve-tests1](https://cloud.githubusercontent.com/assets/6125097/23378212/ec2a5738-fd32-11e6-924e-568b89dbb5bb.png)
Linebreak added
![improve-tests2](https://cloud.githubusercontent.com/assets/6125097/23378213/ec2ed948-fd32-11e6-825e-016a54d39057.png)

I assume this is a regex-based test and run against the original source code.

A fix could be to use regexes like `/<br />/.test(originalSourceCode)` and `/<hr />/.(originalSourceCode)`. Then the test-messages could be changed to "The div should contain a **valid** br tag." and "The div should contain an **valid** hr tag."

**Comment by bonham000** [comment]
So it wasn't exactly regex based, at least the tests for the `br` and `hr` weren't, but this is a good point and I just updated the tests to simply test for the presence of these elements. It should work properly now.
