### ISSUE TITLE
Improve instruction for "Challenge: Use PropTypes to Define the Props You Expect"

### ISSUE THREAD

**Issue by Greenheart** [bonham000/fcc-react-tests-module#182]
In the following sentence from the last paragraph of the description, "method" should probably be replaced with "property", as `isRequired` seems to be a property.
> The isRequired method tells React that handleClick is a required property for that component.

However, if `React.PropTypes.func.isRequired` really is a method, this doesn't apply.

**Comment by bonham000** [comment]
Yeah, I agree — this is good to clarify I've updated this part of the description.
