### ISSUE TITLE
Improve instructions for "React 27: Use State to Toggle an Element"

### ISSUE THREAD

**Issue by Greenheart** [bonham000/fcc-react-tests-module#185]
The last part of the hint uses the term "fat arrow function". This should probably be changed as JS doesn't have have multiple kinds of arrow functions.

It would also simplify the instructions a tiny, tiny bit.

Refer:
```diff
-or use a fat arrow function
+or use an arrow function
```

**Comment by bonham000** [comment]
Changed it to "an ES6 arrow function" — thanks!
