### ISSUE TITLE
Incorrect formatting for Note in "React 47: Use Array.map() to Dynamically Render Elements"

### ISSUE THREAD

**Issue by Greenheart** [bonham000/fcc-react-tests-module#186]
The Note in the final paragraph isn't properly formatted.

**Comment by mapadev** [comment]
My english isn't perfect, but this sentence in 4th paragraph looks weird to me:

> When the user enters a comma-separated list into the textarea, a button click and the handleSubmit() method take that list, split it at the commas, and store it as an array within MyToDoList's state object.

Is it correct?
For me it seems like it's partially description of what is happening in handleSubmit() and partially instruction to modify handleSubmit() - but this part of code in seed doesn't require user modification. Maybe it did in the past?

**Comment by Greenheart** [comment]
Good catch @gogolab, I agree.

onsdag 1 mars 2017 skrev gogolab <notifications@github.com>:

**Comment by bonham000** [comment]
Cool, @gogolab you're right about this I just removed that line.
