### ISSUE TITLE
Unable to pass last test case in "React 48: Give Sibling Elements a Unique Key Attribute"

### ISSUE THREAD

**Issue by Greenheart** [bonham000/fcc-react-tests-module#187]
1. The following doesn't pass the tests:
```js
frontEndFrameworks.map((fw, i) => <li key={i}>{fw}</li>)
```

2. Not even the solution passes all tests.

**Comment by bonham000** [comment]
I'm not seeing this the solution code and the code you wrote here both work for me. Is this still not working for you @Greenheart?

**Comment by Greenheart** [comment]
@bonham000 Strange, now this works! :smile:
