### ISSUE TITLE
Improve name of variable in "React 49: Use Array.filter() to Dynamically Filter an Array"

### ISSUE THREAD

**Issue by Greenheart** [bonham000/fcc-react-tests-module#188]
Consider renaming the variable `filterUsers` to `usersOnline` or at least `filteredUsers`. This will improve readability.

Remember to update the description.

**Comment by Greenheart** [comment]
Another issue with this challenge is that it's expecting a `<p>` tag for every user.

As this is a list of content rather than separate chunks of text, the HTML for this challenge could be more semantic by using an `<ul>` to where `<li>`s are rendered for each user.

**Comment by bonham000** [comment]
Awesome, I've made these two changes would you mind looking back over the challenge and seeing if it is all functioning correctly?

**Comment by Greenheart** [comment]
@bonham000 Thanks, working great! :smile:
