### ISSUE TITLE
Consider adding an example to "Render React on the Server with renderToString"

### ISSUE THREAD

**Issue by Greenheart** [bonham000/fcc-react-tests-module#189]
It was pretty obvious what to do, but I can imagine some may want an example showing how the `renderToString()` method works. Another way to tackle this would be to explain what arguments the method expects.

**Comment by bonham000** [comment]
I'm not really sure what you're thinking we could add here. Do you have a more specific example of your suggestion?

**Comment by Greenheart** [comment]
@bonham000 I'm thinking of something like
> `renderToString()` takes the parameters X and Y.

**Comment by bonham000** [comment]
Cool, I added a line to make it a little more clear.
