### ISSUE TITLE
Unclear instruction for "Redux 17: Copy an Object with Object.assign"

### ISSUE THREAD

**Issue by Greenheart** [bonham000/fcc-react-tests-module#190]
Especially this sentence is unclear:
> If you write this method and pass an empty object `{}` as the first argument, the target is an empty object.

Also the next sentence could be reworked
> Basically, you use the method to assign and return a new object.

I suggest we look for how we could explain `Object.assign()` in a simpler way and combine some of the current sentences and still have the same meaning.

**Comment by bonham000** [comment]
I revised the wording here.
