### ISSUE TITLE
Code formatting for example in "React Redux 06: Map Dispatch to Props"

### ISSUE THREAD

**Issue by Greenheart** [bonham000/fcc-react-tests-module#194]
1. Fix indenting.
2. Use ES6 simplified functions in object literals.

```diff
{
-submitLoginUser: function(username) {
- dispatch(loginUser(username));
- }
+  submitLoginUser(username) {
+    dispatch(loginUser(username));
+  }
}
```

**Comment by bonham000** [comment]
1. Fixed the indentation.
2. Writing it as it currently is makes it explicitly clear that we're returning an object with a property `submitLoginUser` which is a `function`. I'm inclined to keep it this way because I think it is more clear what is happening.

What do you think?

**Comment by Greenheart** [comment]
@bonham000 Sure, these optimizations belong in camper's own projects :blush: We should focus on teaching what's unique to these topics

**Comment by bonham000** [comment]
Sounds good!
