### ISSUE TITLE
Question: Adding free EggHead videos to intro

### ISSUE THREAD

**Issue by benschac** [bonham000/fcc-react-tests-module#197]
Hey, I know the whole idea here is to use FFC content.  Especially with Redux I think it might be helpful to note/document the egghead series by Redux's creator as well as the official documentation (which also references the video series).

Just an idea.  Using both FCC and the video series together helped me understand Redux a lot better.

https://egghead.io/courses/getting-started-with-redux

**Comment by bonham000** [comment]
@benschac I agree with you for the most part however Quincy is explicitly looking to limit external links within challenges as they will draw people outside of the FCC curriculum. This idea is that within FCC challenges one should be able to progress pretty quickly from one challenge to the next without encountering trails that lead elsewhere.

I think outside resources will be necessary, but more likely that campers will find them via Forum/Gitter/their own searches.

**Comment by benschac** [comment]
What about just having the official docs on the front-page.  Or is that too
veering folks off the FCC path.

**Comment by bonham000** [comment]
That's possible too but again probably best decided by Quincy or someone more in charge of the overall FCC curriculum design. I would recommend raising an issue there (especially after these challenges are finally merged into FCC) so it can be better decided upon.

**Comment by benschac** [comment]
for sure.  Thanks :D
