### ISSUE TITLE
Challenge 2 : Typo and Instruction

### ISSUE THREAD

**Issue by alayek** [bonham000/fcc-react-tests-module#20]
The second challenge, titled **Challenge: Create a Complex JSX Element**, has this:

```js
...
The div contains an h1 tag as the second element.
The div contains an p tag as the second element.
...
```

---

I entered the following solution:
```jsx
<div>
  <h1>
    Hello
  </h1>
  <p>
    Hello
  </p>
  <ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
  </ul>
</div>
```

It did not work.

Solution code shows this:

```jsx
const JSX = (
<div>
	<h1>Hello JSX!</h1>
	<p>Some info</p>
	<ul>
		<li>An item</li>
		<li>Another item</li>
		<li>A third item</li>
	</ul>
</div>);
```

The `const JSX = (` part should ideally be assumed. Or leave that part like this in the codemirror text area

```js
const JSX = (
{/* Add code below */}

{/* Add code above */}
);

**Comment by bonham000** [comment]
The instructions and tests for this challenge make it clear we're looking for a `const JSX` to return a `div`. Did you still think it would be better to add something like:

``` javascript
const JSX = (
{/* Add code below */}

{/* Add code above */}
);
```

instead?

**Comment by alayek** [comment]
I think it's better to be explicit that you need the `const JSX = (` - either we put that in the code ourselves or spell it out clearly in the instructions.

**Comment by bonham000** [comment]
So right now the first line in **Instructions** says: `Define a new constant JSX` and the second test is `The constant JSX returns an <div> element.`

We could modify that test to read `There is a constant named JSX which returns a <div> element`

What do you think? I thought it was already clear that we wanted a new `const` defined.
