### ISSUE TITLE
Question about Challenge-Redux 17 & 18

### ISSUE THREAD

**Issue by ccrubby214** [bonham000/fcc-react-tests-module#204]
hi @bonham000 , thanks for your previous reply.  I have finished the part of Redux challenge, and when I studied in Redux 17 & 18 ,  I found a place easy to misunderstand as below:

`const wakeUp = () => {
	return {
		type: ONLINE,
	}
};`

after the K/V-type: ONLINE，there is a comma, and I know it is ok in most of browsers currently, but it still not compatible in the browsers base on the IE6~7 core;  And another reason is , when I first prepared to finish the challenge, at first, I think I need to type a new K/V here as ```status: 'online'```， so I think if remove the comma will be better to understand the challenge, not only me, but also others : )

thanks

**Comment by bonham000** [comment]
@ccrubby214 yes, you are totally right about that. Nice job finding this, I agree that removing the comma is probably a good move. I just updated the code to reflect this change. Thanks for bringing this up!
