### ISSUE TITLE
Syntax highlighting not working properly when implementing fat arrow functions

### ISSUE THREAD

**Issue by b4ux1t3** [bonham000/fcc-react-tests-module#205]
Spotted in React 28: Write a Simple Counter, but it works in all of the editing sections. Every method following a fat arrow function loses its syntax highlighting. The same does not happen when declaring a normal method.

[Image](https://i.imgur.com/xE0Hw2O.png)

[Normal methods don't break highlinghting](https://i.imgur.com/Ntjp8D9.png)

**Comment by bonham000** [comment]
Yes, we've noticed this a while ago... it has to do with (I think) the fact that writing `class` methods as ES6 arrow functions is actually a feature provided by a future JavaScript version (as noted in Challenge 26). So I think this is breaking the syntax highlighting... which is managed by a third party library so this is not a major concern.

**Comment by b4ux1t3** [comment]
Gotcha, I wasn't sure if you'd made the editor yourself or not.
