### ISSUE TITLE
Challenge 3 : Where to put the comment

### ISSUE THREAD

**Issue by alayek** [bonham000/fcc-react-tests-module#21]
In the instruction it says 

>Instructions: We've provided a JSX element similiar to what you just wrote. Add a comment after the `h1`.

I added the comment like this:

```jsx
const JSX = (
<div>
	<h1>This is a block of JSX</h1>
	<p>Here's a subtitle</p>
  {/* hey */}
</div>);
```

Solution code:
```jsx
const JSX = (
<div>
	<h1>This is a block of JSX</h1>
	{ /* this is a JSX comment */ }
	<p>Here's a subtitle</p>
</div>);
```

Does it have to be just after `h1` and before `p`, or is it okay to put it anywhere within the JSX?

---
A small typo: 
```diff
- similiar
+ similar
```

**Comment by ghost** [comment]
@alayek are you asking whether it should say "Add a comment directly after the h1?" I added the comment after ```<p>``` and it still functioned properly, which is correct for the current instructions.

**Comment by bonham000** [comment]
I agree with @SEGrooms adding a comment after the `p` tag still works for me here. Can you confirm if that does not work for you @alayek?

**Comment by alayek** [comment]
@bonham000 @SEGrooms works for me no matter where I put it, as long as it's after `h1`, and within the closing `</div>`. I would recommend putting it clearly that this is,
- either, just after `<h1>`
- or, anywhere after `<h1>`

Whatever it is, that needs to be clear from the instructions IMHO. I know that it probably sounds like a small nitpick, but over time, you would find confused people asking about it in main chatroom and someone having to clear it up over and over again.

**Comment by bonham000** [comment]
I totally agree with you @alayek that's exactly why we're looking to get feedback from everyone on these now. I will change the wording on this and I am about to push changes to Surge. Also... after considering live preview on JSX challenges I just added that feature after realizing it would be easy to add, so that will be there as well.

**Comment by PorgJuice** [comment]
It should also be clear that the student is **not** to comment out the existing markup, but to have the comment elsewhere within the `<div>` tags.  This was confusing to me as I thought I was supposed to comment out the `<h1>` or `<p>`.

**Comment by bonham000** [comment]
Gotcha, I will update it to try and reflect this.
