### ISSUE TITLE
About code consistency in React-Redux 03&04

### ISSUE THREAD

**Issue by ccrubby214** [bonham000/fcc-react-tests-module#210]
hi @bonham000 , I found a little code inconsistency in React-Redux 03&04 as below:

in challenge 03, you use a concise way to write "message: message" :
`const addMessage = (message) => {
	return {
    type: ADD,
    message
  }
};`

and in challenge 04, you use the "message: message" again, I just think it might make people confused if he don't know the concise way just as me(I searched it in google : ) )  , thanks

**Comment by bonham000** [comment]
Yes, this is a good point. I'll update RR 04 to use the concise syntax. This syntax is fairly common and very useful, so I think it's good to demonstrate here so people are aware of it, but also good to be consistent as you pointed out here.
