### ISSUE TITLE
Redux 01: Add link to "ES6 section"

### ISSUE THREAD

**Issue by pablopaul** [bonham000/fcc-react-tests-module#212]
Concerning https://github.com/bonham000/fcc-react-tests-module/blob/master/src/challenges/redux/Redux_01.js#L26

> If you're not familiar with default arguments, you can refer to the ES6 section.

Which is the mentioned `ES6 section`? I cant find it right now. 
`ES6 section` should be a link.

**Comment by bonham000** [comment]
I agree, this is somewhat misleading. This basically indicates the ES6 section in the freeCodeCamp Curriculum, which, now, is currently in Beta (technically along with these React challenges). Eventually......... these will all be together within the FCC platform, so this should make more sense and we can add a direct link to the ES6 challenges at that time if needed.

**Comment by pablopaul** [comment]
@bonham000 Why not add the link to the beta now and add a @TODO do update it later?

**Comment by bonham000** [comment]
@pablopaul The other reason is that there is a goal of minimizing links within the challenges. However, for now I'll add a link to this challenge within Beta.
