### ISSUE TITLE
Challenge #13: Correct solution not accepted.

### ISSUE THREAD

**Issue by rorm** [bonham000/fcc-react-tests-module#213]
Hey there guys, excited that this course is on its way! Thank you

![screen shot 2017-04-24 at 08 41 56](https://cloud.githubusercontent.com/assets/24595643/25326908/062fefa4-28ca-11e7-9f73-476a74866859.png)

For some reason, I get this error. My solution code is identical save the added empty lines.

**Comment by bonham000** [comment]
@rorm yes, it seems the tests were a bit inexact on this one. Your code fails because the `h1` was not wrapped within the `div` that was originally present in the seed code. But the test is really looking for the name of the component. I've modified the test and fixed this.
