### ISSUE TITLE
Exercise 8

### ISSUE THREAD

**Issue by nathanhannig** [bonham000/fcc-react-tests-module#216]
The solution code has the return statement and parenthesis starting before the comment // change code below this line.

I believe they need to be moved after the beginning comment as they are code that must be created. by the user.

```
  render() {
    return (
	    // change code below this line
	    <div>
	    	<h1>Hello React!</h1>
	    </div>
	    // change code above this line
    );
  }
```

**Comment by bonham000** [comment]
Thanks for pointing this out, I've fixed it now.
