### ISSUE TITLE
React.PropTypes is depreciated (Exercise 18 and 20)

### ISSUE THREAD

**Issue by nathanhannig** [bonham000/fcc-react-tests-module#217]
As of April the new version of React depreciates React.PropTypes.

React documentation now shows the use of the prop-types library.
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by bonham000** [comment]
@no-stack-dub-sack what do you think we should do about this?

**Comment by bonham000** [comment]
@breakpoint25 this is a good point... what do you think we should do about this?

We may be able to provide the `PropTypes` as a global object that you can reference directly for these challenges, and make a note about the recent change.

**Comment by bonham000** [comment]
I've made some changes to reflect this deprecation. It allows the challenges to work by simply referencing `PropTypes`, and there is a note in challenge 18 about the deprecation and new way to import `PropTypes`. I'll close this for now!
