### ISSUE TITLE
Exercise 43 - Seems correct to me. 

### ISSUE THREAD

**Issue by carpben** [bonham000/fcc-react-tests-module#219]
The checking shows something is wrong, but it seemed to me to be identical to the solution. Here is a screenshot. 
![image](https://user-images.githubusercontent.com/13496178/27001794-494d88ee-4dfc-11e7-9fd4-87f531c83a93.png)

**Comment by bonham000** [comment]
@carpben line 33 `return` is spelled `reutrn`. Let me know if that doesn't fix it!

**Comment by bonham000** [comment]
Going to close this, let me know if there are any more issues!
