### ISSUE TITLE
React Challenge 20 seems to have an error recognizing "PropTypes" when that is included

### ISSUE THREAD

**Issue by khaduch** [bonham000/fcc-react-tests-module#226]
I was trying to go through the lessons again to refresh, and lesson 20, "Using Props with Stateless Functional Components" will not render when the `Camper.propTypes` are defined, even when loading the solution code.
Errors in the dev console report the error "Live rendering failed ReferenceError: PropTypes is not defined"

**Comment by AryanJ-NYC** [comment]
Did you import PropTypes? Can you show us your code?

**Comment by khaduch** [comment]
Thank you for your reply.

I just loaded the project "solution code" after thinking that I had the correct code from my own attempt and it will not pass - rather, it will not not display the anticipated output in the output area. The devtools console shows the error that I mentioned. This is the step-by-step description of what I tried.

Immediately after loading the solution code for Lesson 20, all of the tests are marked as passing, but the output does not get rendered to the output area on the screen. The error given in the console is `Live rendering failed ReferenceError: PropTypes is not defined`

I then added the string that was given in Lesson 18 at the top of the code window - import string: 
`import React, { PropTypes } from 'react';`

and the error in the console is now:
`Live rendering failed ReferenceError: require is not defined`

It is not clear to me how to import PropTypes - perhaps just adding it into the code window is not the correct place? I do not fully understand the user interface for the coding and test environment.  I am also trying to set this exercise's solution up in a CodePen project and still not having success, searching for answers has been attempted with no success, but I'll admit that I couldn't spend a lot of time on it last night.  Any helpful advice / fixes for this would be appreciated.   Thanks!

**Comment by khaduch** [comment]
In case it isn't clear, I'm using / referring to the Lesson 20 from [this link](http://hysterical-amusement.surge.sh)

**Comment by bonham000** [comment]
Hey @khaduch, thanks for bringing this up. Recently in React v15 `propTypes` was separated out from React into it's own module. This deprecation affected these challenges, and although we (crudely) fixed it for the tests we missed it for the live preview. I've fixed it now for this and the other challenges that utilize `propTypes`. The working version should be live soon. Thanks for reporting this!
