### ISSUE TITLE
React 30: Using <form> tags with onSubmit listener causes page refresh

### ISSUE THREAD

**Issue by AryanJ-NYC** [bonham000/fcc-react-tests-module#227]
Entering something like:

```jsx
class MyForm extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			input: '',
			submit: ''
		};
	}
	handleChange = (event) => {
		this.setState({
			input: event.target.value
		});
	}
	handleSubmit = () => {
		this.setState({
			submit: this.state.input
		});
	}
	render() {
  	  return (
	    <form onSubmit={this.handleSubmit}>
              <input
        	value={this.state.input}
        	onChange={this.handleChange} />
              <button>Submit!</button>
              <h1>{this.state.submit}</h1>
	    </form>
         );
      }
};
```

and pressing the rendered submit button causes a page refresh.

**Comment by bonham000** [comment]
@AryanJ-NYC thanks for trying to fix this. If we prevent default behavior for form submission we should be able to get around this. For instance:

``` javascript
	handleSubmit = (e) => {
        e.preventDefault();
		this.setState({
			submit: this.state.input
		});
	}
```

This is pretty normal to prevent form submission directly and then handle the form contents in some other way in React applications, so this is a good opportunity to introduce form submission and prevent default behavior together.

What do you think?

**Comment by AryanJ-NYC** [comment]
That may work but users are still allowed to not prevent default and refresh the entire page. Is that something you want users to be able to do? If so, I'll take a look again tomorrow and see if I can write tests for it.

**Comment by bonham000** [comment]
@AryanJ-NYC yeah, I think that would be OK. We should just explain in the intro/instructions that if they fail to include `preventDefault()` it will refresh the page.

**Comment by bonham000** [comment]
Modified challenge.
