### ISSUE TITLE
React challenge alpha #35 incorrectly accepts a string as a parameter to add or remove event listener call

### ISSUE THREAD

**Issue by nemogoc** [bonham000/fcc-react-tests-module#228]
Copied from issue 15793 in the main fcc project.

#### Challenge Name
http://hysterical-amusement.surge.sh/ 
React challenge number 35 - Add Event Listeners

#### Issue Description
I hope this is the right place for this issue. 

The second parameter for the remove/addEventListener calls will accept the strings "handleKeyPress" or "handleKeyPress()" as correct input. All tests pass with either of those strings, allowing you to move on to the next challenge. Code sample that passes all tests (but does not operate as expected) attached below.

#### Your Code

```js
class MyComponent extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			message: ''
		};
	}
	// change code below this line
	componentDidMount() {
		document.addEventListener("keydown", "handleKeyPress")
	}
	componentWillUnmount() {
		document.removeEventListener("keydown", "handleKeyPress()")
	}
	// change code above this line
	handleEnter = () => {
		this.setState({
			message: this.state.message + 'You pressed the enter key! '
		});
	}
	handleKeyPress = (event) => {
    if (event.keyCode === 13) {
    	this.handleEnter();
    }
  }
  render() {
    return (
			<div>
				<h1>{this.state.message}</h1>
			</div>
    );
  }
};

```
#### Screenshot

<img width="1636" alt="screen shot 2017-08-23 at 15 16 30" src="https://user-images.githubusercontent.com/1668286/29636401-183a3ae6-8816-11e7-9445-898a77ba1072.png">

**Comment by bonham000** [comment]
@grumpwagon cool, thanks for posting this here! I can look into this unless you'd like to investigate and try to pull request a fix. It will involve the test cases written for those specific tests.

**Comment by nemogoc** [comment]
I'm not going to be able to investigate it for a couple of weeks (going out of town), so feel free to take a look. If I get some time before you've had time, I'll submit a PR, but don't wait on me.

**Comment by bonham000** [comment]
Thanks for finding this, I've fixed it now.
