### ISSUE TITLE
Not teaching an async or routing library.

### ISSUE THREAD

**Issue by conradbkay** [bonham000/fcc-react-tests-module#229]
<b>react-router and redux-saga/redux-thunk</b> are not being taught currently. These tools make using react tremendously easier. And<i> having an advanced section</i> for tools like these would be a great help. And maybe a section about <b>testing components using snapshot testing and enzyme</b>. Or a similar technology.
 I would be happy to create these sections but am wondering if I should go through the effort to do this. I could even make challenges for libraries like material-UI, react-motion, or redux-form. All feedback is welcome.

**Comment by bonham000** [comment]
@conradkay I think this is a great idea. The challenge Redux 12 actually does use `Redux-Thunk` to explain how asynchronous actions can work with Redux. But I think advanced topics like `Redux-Saga`, `Rx`, or routing would be good additions, along with testing.

However, eventually, these challenges will be merged into the main freeCodeCamp codebase. I think for the time being we should wait to make any substantial changes or additions to this React/Redux curriculum.

Another potential concern to be aware of is that any changes to a library could cause problems with challenges written before that change. We've already experienced that with these React challenges (React v15), even though React's API is pretty stable at this point. Other libraries (React Router, e.g.) have changed more frequently in the past few years). This is just another consideration that would need to be taken into account before committing to write challenges.
