### ISSUE TITLE
Lesson 37 - Rendering and Performance in React 

### ISSUE THREAD

**Issue by carpben** [bonham000/fcc-react-tests-module#231]
**According to React's documentation**(https://facebook.github.io/react/docs/rendering-elements.html)

> React DOM compares the element and its children to the previous one, and only applies the DOM updates necessary to bring the DOM to the desired state.

**Acording to lesson 37** 

> the default behavior is that your component re-renders when it receives new props, even if the props haven’t changed. You can use shouldComponentUpdate() to prevent this by comparing the props.

These second statement seems to contradict the first, and requires clarification. 
I understand that `shouldComponentUpdate` can prevent the components render function from running, and the component would not even be rendered to the virtual dom. I think it should be clarified that there are two different levels of rendering, and that `shouldComponentUpdate` deals with updating to the virtual dom.

**Comment by carpben** [comment]
I also opened a discussion in the forum. Here's a link: 
https://forum.freecodecamp.org/t/lesson-37-in-the-react-beta-rendering-and-performance-in-react/147681

**Comment by bonham000** [comment]
[From React docs](https://facebook.github.io/react/docs/react-component.html#setstate): 'By default, when your component's state or props change, your component will re-render.'

React's use of a virtual DOM to actually determine how it will perform re-renders is I would say part of the implementation magic you get with React. It's totally abstracted away from you as you write React code. Basically, the key notion is that React manages DOM updates efficiently, through its use of the virtual DOM.

Meanwhile, as you reason about the code you're writing, you know that `state` or `props` changes trigger component re-renders, and if you need to intervene for some reason, you have to use the lifecycle methods, such as `shouldComponentUpdate`, to do so. Therefore, the primary message for this challenge I think still makes perfect sense.

**Comment by carpben** [comment]
Thanks for your response. 
I'm not a React experienced programmer, but I tend to disagree: 

- The quote you mentioned is valid, but in the next sentence it is made clear that they refer to the render funciton of the component. It depends what you mean by render, and before React if I'd read render I'd assume the dom. 
- Also another FCC member thinks the same, as you can read in the forum thread.
