### ISSUE TITLE
React challenge 38

### ISSUE THREAD

**Issue by japickering** [bonham000/fcc-react-tests-module#233]
It turns out the author's code can pass with HTML text "Mellow yellow" but with the inline CSS specifying red and font size 72.
The user also has to fix a typo in the inline style syntax so that style= comes before the {{ for this to pass all the tests (the code snippet provided in the live editor is misleading).

**Comment by bonham000** [comment]
@no-stack-dub-sack tagging you since I believe you wrote this challenge.

**Comment by bonham000** [comment]
@japickering I'm pushing an update to this. It should resolve the problems raised here.
