### ISSUE TITLE
Redux 14 challenge: Do not Mutate state

### ISSUE THREAD

**Issue by japickering** [bonham000/fcc-react-tests-module#234]
Where is this code solution drawn from? There is no console output for the code that passes the tests that would provide some level of proof that the concept works.
I looked into the official docs on Immutable Data and couldn't find any discussion on using concat() to return todo actions. If you're going from writing counters in Redux to the next challenge shouldn't it follow a natural topic progression?
http://redux.js.org/docs/faq/ImmutableData.html

**Comment by bonham000** [comment]
The `concat` method is an immutable operation, based on how the JS spec is written: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat

This is generally acceptable for immutable operations on arrays of data, like the ones described here.

**Comment by japickering** [comment]
@bonham000 True and I have used `concat() `before but in the Mozilla dev link you've quoted the data arrays are explicitly documented in the code example so it's obvious that 2 arrays need to be combined together. 

In this Redux challenge the learner has no such information about the problem. The answer was passing a todo action into a state.concat() but how would you even know that the todo action is in array format to arrive at the solution to it? 

e.g. if you do this:
`const immutableReducer = (state = ['Do not mutate state!'], action) => {
	switch(action.type) {
		case ADD_TO_DO:
      console.log(action.todo);
			return state.concat(action.todo);
		default:
			return state;
	}
};`

You get this in the console log:
__TEST__TO__DO__

**Comment by bonham000** [comment]
@japickering I think you have some valid points here. I just made some updates to the challenge. Take a look and let me know what you think! Thanks for bringing this up.

**Comment by japickering** [comment]
@bonham000 Thanks Sean that's much clearer. If I do `console.log(state.concat(action.payload));` 
 I get the following code..
`["Go to the store", "Clean the house", "Cook dinner", "Learn to code", "__TEST__TO__DO__"]`

**Comment by bonham000** [comment]
Great! I'm going to close this now. Please let me know if you find anything else that you think should be improved.
