### ISSUE TITLE
React 36 - nextProps issue

### ISSUE THREAD

**Issue by u-rogel** [bonham000/fcc-react-tests-module#235]
The student can also pass the lesson by using `nextProps` once, in the `console.log` or as a parameter in the func.

so I suggest to change the test from this:
```
lifecycleChild.includes('nextProps') === true
```
to this:
```
lifecycleChild.match(/nextProps/g).length === 2
```
which requiring the user to use `nextProps` twice which is what should happen.

**Comment by u-rogel** [comment]
I am new here, so not sure if I should send a PR for that or you wanna fix it on your own since it's a tiny fix.

**Comment by bonham000** [comment]
@cowCrazy thanks for bringing this up, I think your suggestion is a good improvement. Feel free to match a PR for this change. I think it will improve the test — however, many of the tests are not completely foolproof. For instance, this suggestion could still be broken as follows:

``` javascript
componentWillReceiveProps(nextProps) {
   console.log(this.props);
   // nextProps;
}
```

Feel free to just implement and PR the solution you suggested, however. Thanks for bringing this up!

**Comment by u-rogel** [comment]
@bonham000 I also noticed it is not completely foolproof, if you want I can try and rise the foolproof level with something like that:
1. For `nextProps` [as a function parameter](https://regex101.com/r/PA1g6l/1/)
2. For `nextProps` in a [`console.log` call](https://regex101.com/r/twIMC7/2/)

**Comment by bonham000** [comment]
@cowCrazy yes — sorry for the delay — feel free to improve the test here, but don't feel obliged.

**Comment by bonham000** [comment]
Resolved in above-mentioned PR!
