### ISSUE TITLE
Redux 9

### ISSUE THREAD

**Issue by u-rogel** [bonham000/fcc-react-tests-module#236]
I think there is something unclear with the 4th test case. The user is told one thing should happen but eventually something different happens and the test passes.

> 'An action of type ADD should be dispatched three times and a text message should be logged to the console on each dispatch.'

But when I click 'Test code' I see 4 logs to the console, I believe this comes from an extra `store.dispatch({type: ADD});` in test 1:
```
// test 1:
	try {

		const initialState = store.getState();
		>> store.dispatch({type: ADD}); <<
		const newState = store.getState();

		assert.strictEqual(newState, initialState + 1, error_1);

		testResults[1].status = true;
	} catch (err) {
		passed = false;
		testResults[1].status = false;
	}
```

So I think if it is possible to remove one `store.dispatch({type: ADD});` before the `eval()` of test 3, than you can compensate for the one added for test 1. So I suggest changing the test 3 code as follow:
change these two lines:
```
const consoleReplaced = code.replace(/console.log/g, 'message');

assert(log.length === 3 && typeOf === 'string', error_3);
```
to:
```
const consoleReplaced = code.replace(/store\.dispatch\({type: ADD}\);/, '').replace(/console.log/g, 'message');
assert(log.length === 2 && typeOf === 'string', error_3);
```
This would run the `dispatch` only twice, plus the one before would make three, as the learner expects from the instructions.

**Comment by bonham000** [comment]
@cowCrazy the original three console logs are actually coming from the evaluation of the code in line 120. I changed this so it is working as you would expect by making a different change.
