### ISSUE TITLE
Render to DOM node failing on all tests requiring it

### ISSUE THREAD

**Issue by MrSkinny** [bonham000/fcc-react-tests-module#239]
As example, here is the submitted code on React-06:
```
const JSX = (
<div>
	<h1>Add a class to this div</h1>
  <br />
  <hr />
</div>);

ReactDOM.render(JSX, document.getElementById('challenge-node'));
```

Failing test:
```
The provided JSX element should render to the DOM node with id 'challenge-node'.
```

Using Chrome Version 61.0.3163.100
To confirm no typos, this code works on Codepen: https://codepen.io/anon/pen/yzZZjE?editors=1010

**Comment by MrSkinny** [comment]
Resolved by starting each test first clicking "Reload Seed"

**Comment by bonham000** [comment]
@MrSkinny based on your second comment this could be a problem with the app itself, caused by some refactoring I did a few weeks ago. You should be to load one of these challenges, write the solution, and it passes, without having to reload the seed code.

**Comment by MrSkinny** [comment]
Yeah, @bonham000 it doesn't seem like the intended effect -- clicking "Next Challenge" doesn't reset the seed for me.

**Comment by bonham000** [comment]
@MrSkinny I believe I've fixed these issues. There were definitely some problems navigating between challenges. Feel free to take a look at the app and let me know if you find anything else. Thanks for pointing this out!
