### ISSUE TITLE
Redux challenge 7, potentially misleading text in test description

### ISSUE THREAD

**Issue by Pethaf** [bonham000/fcc-react-tests-module#240]
The description says that the the reducer should return an object with the authenticated property set to either true or false. The test description says

    Dispatching loginUser should update the login property in the store's state to true.
    Dispatching logoutUser should update the login property in the store's state to false.

This is a bit missleading as test descriptions could be interpreted as stating that the reducer should return an object with a login property.

A simple fix would be to change the relevant test descriptions.

**Comment by bonham000** [comment]
@Pethaf yes I agree with you. Good job finding this, I've made the changes to these tests, feel free to take a look and open any new issues if you find something else. Thank you!
