### ISSUE TITLE
Redux Challenge 10, introductory text might be unclear

### ISSUE THREAD

**Issue by Pethaf** [bonham000/fcc-react-tests-module#241]
The following section seems a bit unclear to me
  
    The name you give to the keys will be used by Redux as the name for the associated piece of state. 

What does this mean? And how is this used when a message is dispatched to the store?

**Comment by bonham000** [comment]
@Pethaf it means that if you define a reducer with the name `users`, and then pass this to redux your state tree (an object) will have a key `users` in it, whose state is controlled by that users reducer. Feel free to submit a PR to clarify the language if you think we can explain it better!
