### ISSUE TITLE
Challenge 6: Solution code is incorrect

### ISSUE THREAD

**Issue by ghost** [bonham000/fcc-react-tests-module#27]
The solution code doesn't properly fulfill the fifth test.

**Comment by alayek** [comment]
I think it also has a destructuring error.

```js
const DemoComponent = function(props) {
  // Using ES6 object destructuring to assign myClassName to props.myClassName
  const myClassName = {props};
...
```

The above assumes there is something (probably a string class name) called `this.props.props` and `myClassName` is being assigned to that value / string.

Ideally, it should be something like this

```js
const DemoComponent = function(props) {
  // Using ES6 object destructuring to assign myClassName to props.myClassName
  const myClassName = {myClassName};
```

And the parent component would call it as 

```jsx
<DemoComponent myClassName={/* some string */} />
```

**Comment by bonham000** [comment]
So this works for me right now, the solution or typing it in manually for challenge 7.

**Comment by ghost** [comment]
Sorry guys, I meant number 6

**Comment by bonham000** [comment]
The test on rendering the JSX to the DOM?

**Comment by ghost** [comment]
Correct, it isn't working. I'm not sure why. I'm using chrome on OSX.

**Comment by alayek** [comment]
Works for me on Chrome, OSX Sierra

**Challenge: Learn About Self-Closing JSX Tags**

That is 6, right?

**Comment by ghost** [comment]
Correct. React 06: Learn About Self-Closing JSX Tags. I filled in the solution manually and it didn't work. I pressed "Solution Code" and the solution code was identical to my solution, but isn't render JSX to the DOM.

I'm running  macOS Sierra v.10.12.1 and Chrome v.54.0.2840.98 (64-bit)

**Comment by alayek** [comment]
@SEGrooms it's getting a bit hectic communicating via GitHub issues in real time 😄 

Up for a call or [chat](https://gitter.im/alayek)?

**Comment by bonham000** [comment]
We could move to Gitter or Slack.

**Comment by ghost** [comment]
Gitter
