### ISSUE TITLE
Challenge 8: Wording issue

### ISSUE THREAD

**Issue by PorgJuice** [bonham000/fcc-react-tests-module#32]
> It is best practice to always call a component's constructor with super and pass in props **_to each_** so the component can be initialized properly. 

The "to each" seems like a typo or relic of a sentence long past.

**Comment by bonham000** [comment]
Actually not a typo... the intended meaning was: call `constructor()` and `super()`, passing in `props` to each. How does the following sound:

It is best practice to always call a component's constructor with super, passing `props` to both so the component can be initialized properly.

**Comment by PorgJuice** [comment]
Ah yes, that makes a lot more sense 👍
