### ISSUE TITLE
Challenge 10: Wording

### ISSUE THREAD

**Issue by PorgJuice** [bonham000/fcc-react-tests-module#33]
>The use of compositions allow us to decompose a UI into separate components, allowing us to separate our code from our logic.

The first _allow_ should be _allows_ to agree with the singular subject of the sentence ("_The use of...").  

If I could be so bold, the sentence may sound better thusly:

"The use of compositions allows us to decompose a UI into separate components, and to separate our code from our logic."

**Comment by bonham000** [comment]
Ok, I've applied so edits here to make this read better!
