### ISSUE TITLE
Challenge 13: editing

### ISSUE THREAD

**Issue by PorgJuice** [bonham000/fcc-react-tests-module#36]
I'm not sure what level of nit-picking you're looking for here, so I apologize if these are getting out of hand.

> Once you understand this well you will be prepared to start building more complex React projects.

There ought to be a comma between _well_ and _you_.

Once you understand this well, you will be prepared to start building more complex React projects.

**Comment by bonham000** [comment]
No this is awesome! Bring on all the nit-picking I'd like to clean this up as much as possible before officially merging into FCC platform.
