### ISSUE TITLE
Challenge 18: User can circumvent tests

### ISSUE THREAD

**Issue by PorgJuice** [bonham000/fcc-react-tests-module#39]
The user can simply specify 
```
Items.defaultProps = {
	quantity: 10
}
```

Instead of overriding the property in the JSX.  As the last lesson was about changing default values, a less attentive camper may do this and miss the point of the lesson entirely.

edit: For that matter, I can also just specify the number 10 in the `Items` component.

**Comment by bonham000** [comment]
Ok, good catch. I've updated the test to correct this and pushed any of the recent updates to Surge.
