### ISSUE TITLE
Challenge 6: Comment error

### ISSUE THREAD

**Issue by antonderegt** [bonham000/fcc-react-tests-module#44]
**Challenge name: React 06: Learn About Self-Closing JSX Tags**

The second to last line in the editor of this challenge should be deleted:

```
const JSX = (
<div>
	{/* change code below this line */}
	<p>Welcome to React!<p> <br >
	<img src="https://goo.gl/ErGBQs" alt="React Logo">
	{/* change code above this line */}
</div>
);
// change code below this line
ReactDOM.render(JSX, document.getElementById('challenge-node'));
```

The answer requires code to be changed above that line, as the JSX comments point out.

**Comment by bonham000** [comment]
got it!

**Comment by HKuz** [comment]
@bonham000 - I've made some wording tweaks to this challenge - do you want me to make this change (and edit the instructions so they don't tell the camper to use the ReactDOM.reder function?)

**Comment by bonham000** [comment]
I just changed it actually so if you rebase you should see that extra comment removed but then still go ahead with any other changes!

**Comment by HKuz** [comment]
Okay, will do! I'll have a PR for you shortly with this first set 😄

**Comment by bonham000** [comment]
Ok sounds good!
