### ISSUE TITLE
Challenge 20: Typo/Grammer

### ISSUE THREAD

**Issue by PorgJuice** [bonham000/fcc-react-tests-module#45]
>  ...same UI _everytime_ it receives...

This is actually two words: every time. 

>  ...one of React's important design principle: React is declarative...

_principle_ should be plural here.

> ...It does this in a _predicatable_ way...

_predicatable_ -> predictable

> ...component as a child, however this Camper component...

This is a comma splice and should be split by a period.

> component as a child. However, this Camper component

**Comment by bonham000** [comment]
nice got it!
