### ISSUE TITLE
Challenge 20: Intro is unclear

### ISSUE THREAD

**Issue by PorgJuice** [bonham000/fcc-react-tests-module#46]
I'm confused as to what the intro to challenge 20 is trying to get across, and its the first time I've felt lost in the whole series.  The title is 'Functional Stateless Components', which would lead me to believe that we'll be learning to make FSCs, though we learned that in challenge 7 (there called _stateless functional components_).  The challenge task itself is to assign default props to a FSC, then pass props to it.   This is perfectly reasonable, but it doesn't seem to follow from the intro, and it took me a minute to understand what I was supposed to do.

> Remember at the beginning of this section...

'This section' is ambiguous for the student since there has never been mention of sections until this point.  I argue it's better to point to specific challenges when references covered material. 

> ... when we defined a functional stateless JSX element?

We did define a JSX component, but it wasn't called a "functional stateless JSX element", and this will probably lead to confusion (it has already confused me).  

> We can do the same thing with React Components.

We can do _what_ thing?

The rest of the intro discusses the declarative nature of React and how it separates `state` from `props`, but since state hasn't been discussed before, the distinction is going to be lost to the reader.  For many people, learning React will be the first time that they have to tackle the concept of application state, even though they've built several apps at the point of these lessons.  So, enough criticism.  Here's what _I_ think should be changed:

1) Change the title to be clear about the learning goal (ex. "Default props in functional stateless components")
2) Remove the talk about statelessness and passing data as props.  This challenge should be just about applying what was learned over the last couple of lessons to FSCs.     
3) Add another challenge after this one that discusses application state, why it must be carefully managed, and what this has to do with React.  The challenge itself can be a capstone of what has been learned so far - create a stateful component and a FSC child with default props.  I'm perfectly willing and able to put the time into drafting something like this, if you'd like.  

edit: I didn't move on to the next challenge where state is pretty clearly discussed.  3) May not need to be done.  I think 1) and 2) are still necessary.

**Comment by bonham000** [comment]
I will take a closer look at this and review it later! Thanks a lot for catching all these minor errors everywhere and submitting them here.

**Comment by bonham000** [comment]
This is great insight I agree with you. I'm working on rewriting this challenge right now.

**Comment by bonham000** [comment]
All right, I've rewritten and pushed it back to Surge. Take a look when you get a chance and let me know what you think. Thanks a lot for providing this feedback this is just the kind of insight I was hoping people would have!

**Comment by PorgJuice** [comment]
The rewrite is awesome!  Huge improvement!  Minor inconsistency: While the title calls for a FSC, the solution code has a full React component.  Are the solutions even going to make it to production, or are they just a testing feature?  It doesn't matter for us, but will probably confuse students who check the answer.

```
class Camper extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
   return (
     <div>
       <p>{this.props.name}</p>
     </div>
   )
  }
};
```

**Comment by bonham000** [comment]
So I don't know what will happen to the solutions my guess at the moment is they may end up in the wiki articles or somewhere else.

Either way, good call I will update the solution to reflect this. The distinction between stateless component, functional stateless component, and component ... a little tricky I'll try to make it clear here.

**Comment by bonham000** [comment]
Ok so I have actually rearranged this whole section. We should have been more clear about this distinction from the beginning.

I basically edited all the `props` challenges to use stateless functional components with the exception of the one which discusses using `this.props`, and I moved that one towards the end. I also changed the explanation in 20 and slightly in 21 to hopefully make the distinction/reasons more clear.

If you have a chance could you glance through and see if this makes it more clear? This distinction on components/stateless functional components is really important but can also be a little tricky so I want to be sure it's explained correctly and also doesn't add unnecessary confusion.

**Comment by abadjier** [comment]
I find the following a bit confusing (part of the instructions): 
 "... be sure to include a *p element* which includes..."
I suggest replacing 'p element' with "`<p>`"   or   '`<p>` tag'    to make it more clear.
I found myself wondering for a bit what is a 'p element'

**Comment by PorgJuice** [comment]
I like the latest changes even better, especially the end of the first paragraph that clearly tells the reader what the next paragraph is about.  This gives the reader concrete expectations about the coming information, which helps them structure the information in their heads.  👍 

What I would like to see in that second paragraph is to bring the terminology to the front of each sentence, and also to be italicized.  For example,

>Any function you write which accepts props and returns UI is referred to as a functional stateless component

could be

> A _functional stateless component_ is any function you write which accepts props and returns JSX.

This makes it easier to skim the text for review.

I also changed the term UI to JSX because I feel that has been better defined for the students at this point.  UI isn't bad, and I think readers should get used to thinking of React as outputting UI rather than a whole app, but readers have been seeing JSX returned from functions and that may click easier.  I don't have strong feelings about it, but something to think about.

**Comment by PorgJuice** [comment]
Challenge 21 is great!

**Comment by bonham000** [comment]
Awesome! I like those comments from above I've just updated 20 to reflect this I think it's looking much better now.

**Comment by PorgJuice** [comment]
Perfect 💯

**Comment by bonham000** [comment]
Awesome going to go ahead and close this for now then.
