### ISSUE TITLE
Challenge 26: tests don't pass if double quotes are used in setMessage

### ISSUE THREAD

**Issue by PorgJuice** [bonham000/fcc-react-tests-module#50]
The last test fails with double quotes for the string

```
setMessage = () => {
    this.setState({ message: "Goodbye!" });
  }
```

... but passes with single quotes

```
setMessage = () => {
    this.setState({ message: 'Goodbye!' });
  }
```

Also, it would be worth mentioning that `setMessage` doesn't need a variable assignment keyword (var/let/const) since we're using the `class` syntax.

**Comment by bonham000** [comment]
Ok I've fixed the problem with the test. What do you mean exactly by the last comment on variable assignment?

**Comment by PorgJuice** [comment]
Normally, function expressions are assigned to variables that get declared with keywords.

```
const myFunction = function() {};
const myArrowFunction = () => {};
```

Anyone unfamiliar with the ES6 class syntax may assume this is the case here as well, but it throws an error and all of the tests fail.
