### ISSUE TITLE
Challenge 19: Add link

### ISSUE THREAD

**Issue by abadjier** [bonham000/fcc-react-tests-module#55]
To improve user experience, I suggest adding a link at the end of the Intro, where it says: 
'Please refer to the documentation for an exhaustive list.' 
I think the following is an appropriate link: 
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by bonham000** [comment]
So regardless of my opinion on this the word from Quincy is to keep external links to a minimum so I've deliberately avoided/removed them throughout this curriculum except at the very end where we link to Create React App.

**Comment by abadjier** [comment]
Thanks
