### ISSUE TITLE
Challenge 44: Missing instructions

### ISSUE THREAD

**Issue by PorgJuice** [bonham000/fcc-react-tests-module#60]
The challenge requires students to use the ternary operator, but doesn't show them what it is.

**Comment by bonham000** [comment]
So Peter and Quincy discussed this, a link existed to the ternary operator on MDN but since this is/will be covered in the prior JS curriculum and including an explanation/demonstration here would make the challenge very verbose it was decided to remove the link.

**Comment by PorgJuice** [comment]
I see.  Oh well!
