### ISSUE TITLE
Challenge 23

### ISSUE THREAD

**Issue by abadjier** [bonham000/fcc-react-tests-module#64]
In the Instructions it is not clarified that the 'name' variable should be rendered inside `<h1> ` tag , but the test check for that. 
I guess it is implied that it should be the same as the previous challenge (in challenge 22 it is specified to use `<h1>` tag), but in case the student does not do this challenge right after the previous one, it may be helpful to say it explicitly.

**Comment by bonham000** [comment]
Gotcha, I've changed it to reflect this more specifically. Thanks a lot!
