### ISSUE TITLE
Challenge 44: Typo

### ISSUE THREAD

**Issue by antonderegt** [bonham000/fcc-react-tests-module#65]
**Typo in intro**

Challenge: Use a Ternary Expression to Render Conditionally
Intro: Before moving on to dynamic rendering techniques, lets cover one last way in which we can use built in JavaScript conditionals in order to render what we want, when we want it: the ternary operator. The ternary operator is often utilized as a shortcut for if/else statements in JavaScript, and, while not quite as robust as traditional if/else statements, they are very popular among React developers. One of the reasons for this is **`becuase`**, due to the way it is compiled, if/else statements cannot be inserted directly into JSX code. You might have noticed this a couple of challenges back — any time we used if/else, it was always outside the context of the return statement. That said, ternary expressions can be an excellent alternative if you want to implement conditional logic within your JSX.

**Comment by bonham000** [comment]
cool, got it!
