### ISSUE TITLE
Challenge 12: Rendering before ReactDOM API call

### ISSUE THREAD

**Issue by CodeFay** [bonham000/fcc-react-tests-module#74]
The "Live Preview" section renders the components before the API call ... you do not pass the test, but the disconnect between Live Preview and Passing the Code is confusing.

**Comment by CodeFay** [comment]
Also, once you type in the API call .. the "getElementById" doesn't turn green the way "render" does. (I don't know the technical term for that).

**Comment by bonham000** [comment]
Ah I see what you mean here. I'm going to leave this for the moment because of these issues, live preview and syntax highlighting in the code editor, may be different once the content gets merged with the FCC platform.
