### ISSUE TITLE
React-redux-06, last line of instructions

### ISSUE THREAD

**Issue by ethanrose** [bonham000/fcc-react-tests-module#97]
I submitted a pull request for a typo fix in this one, but actually, even with the typo fix, I don't think this last line makes sense.

Note: We can call this property which will become props whatever we want, but let's called it submitNewMessage here.

**Comment by ethanrose** [comment]
Ah, I see what it's saying now, I think the wording is really confusing though

**Comment by ethanrose** [comment]
maybe remove "which will become props" and put that in a separate sentence?

**Comment by bonham000** [comment]
What about:

``` javascript
This property will become `props` in our component, so we can name it anything. Here, however, be sure to name it `submitNewMessage.`
```

**Comment by ethanrose** [comment]
Much better! or even -

This property will become `props` in our component, so we can name it anything. Let's call this one `submitNewMessage`.

**Comment by bonham000** [comment]
cool got it!
