### ISSUE TITLE
Deleting/replacing a comment within a challenge

### ISSUE THREAD

**Issue by tommygebru** [bonham000/fcc-react-tests-module#98]
comments might be making solutions invalid, i deleted a comment and wrote the solution in the same line, when it didnt pass... i tried the solution button, and the answer was the same

Challenge: Render HTML Elements to the DOM

**Comment by bonham000** [comment]
I'm not sure what happened here I just tried that challenge and it seems to be functioning correctly for me. Make sure you try it on the surge site after a refresh.
